# MediTrack - Digital Medication Tracker

## Project Development Notebook
This notebook is used to develop and test the different parts of the MediTrack application before adding them to the final Python scripts.

### Project Goal
Create an interactive medication tracker using Python and Streamlit that allows users to store, search, manage, and monitor their medications using CSV files, an external medication API, and an LLM API.

In [1]:
project_name = "MediTrack"
project_name

'MediTrack'

In [3]:
print('Development notebook is ready ')

Development notebook is ready

## Main Application Options

The application must provide four main options:
1. Add a new medication to the tracker
2. Search for medications by active ingredient or symptom
3. View all logged medications
4. View a random wellness tip or medication spotlight

## Technologies

- Python
- Streamlit
- CSV files
- requests library
- External Medication API
- LLM API
- GitHub

## External Medication API Discovery

### What is an API?
An API allows one application to communicate with another application and request data.

### What is an Endpoint?
An endpoint is a specific URL or function provided by an API to perform a particular task.

### What is a GET Request?
A GET request asks an API to return information.

### What is JSON?
JSON is a structured format commonly used by APIs to return data. Python can read JSON and access specific values from it.

### Goal for MediTrack
Find an external medication API that can provide useful medication information such as medication names, active ingredients, dosage information, or drug details

### Testing the Requests Library

In [11]:
import requests

print("Requests library imported successfully.")

Requests library imported successfully.

### API Candidate Evaluation

Before selecting an external medication API, the available options will be compared based on:

1. Free tier availability
2. Ability to search by medication name
3. Availability of active ingredient information
4. Availability of useful medication or dosage information
5. Simplicity of the returned JSON data
6. Ease of integration using the requests library

#### Shortlisted APIs

- Drug Information API: FDA Labels and NDC Lookup
- EMA Medicines Data API
- Drug Info and Price History

#### Candidate 1: Drug Information API - FDA Labels and NDC Lookup

Available endpoints:

- `get-drug-by-ndc` - searches for a drug using an NDC code.
- `search-drug-labels` - searches FDA drug label information.

The `search-drug-labels` endpoint appears more suitable for MediTrack because users should be able to search for medication information without knowing an NDC code.

**Status:** Still evaluating

##### Pricing Evaluation

**Basic Plan:** $0.00/month

- 500 API requests per month
- Hard request limit
- Rate limit: 1,000 requests per hour
- Suitable for development and demonstration of MediTrack

The free Basic plan provides enough requests for this project.

**Pricing Result:** Suitable ✅

### Testing the External Medication API

The Drug Information API will now be tested directly from Python using the `requests` library.

The first test will search for "aspirin" and inspect the actual JSON response returned by the API.

In [17]:
import requests

In [19]:
import os
os.listdir(".")

['.env',
 '.gitignore',
 '.ipynb_checkpoints',
 'Development.ipynb',
 'medications.csv',
 'MediTrack Project Roadmap Infographic.png',
 'Open Router API key.txt',
 'Python Project 1 - Part 1 Guidelines.pdf',
 'Python Project 1 - Part 2 Guidelines.pdf']

In [21]:
import getpass

In [23]:
rapidapi_key = getpass.getpass('Enter Your RapidAPI Key :')

Enter Your RapidAPI Key : ········

In [25]:
with open('.env','w') as file : 
    file.write(f'RAPIDAPI_KEY={rapidapi_key}')

In [27]:
os.path.getsize('.env')

63

In [29]:
from dotenv import load_dotenv

In [31]:
load_dotenv()

True

In [33]:
rapidapi_key = os.getenv('RAPIDAPI_KEY')

In [35]:
url = "https://drug-information-api-fda-labels-and-ndc-lookup.p.rapidapi.com/drugs/search"

In [37]:
querystring ={"limit":"10","q":"aspirin"}

In [39]:
headers = {
	"x-rapidapi-key":rapidapi_key ,
	"x-rapidapi-host": "drug-information-api-fda-labels-and-ndc-lookup.p.rapidapi.com",
	"Content-Type": "application/json"
}

In [41]:
response = requests.get(url,headers=headers,params=querystring)

In [42]:
response

In [43]:
response.status_code

200

In [47]:
response.json()

[{'id': '008ee85b-5cac-45a6-a857-a828f8125175',
  'brand_name': 'Low Dose Aspirin',
  'generic_name': 'ASPIRIN',
  'manufacturer': 'P & L Development, LLC',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ASPIRIN'],
  'ndc': ['59726-065'],
  'effective_time': '20240416',
  'purpose': 'Purpose Pain reliever',
  'indications_and_usage': 'Uses for the temporary relief of minor aches and pains or as recommended by your doctor. Because of its delayed action, this product will not provide fast relief of headaches or other symptoms needing immediate relief. ask your doctor about other uses for safety coated 81 mg aspirin',
  'warnings': "Warnings Reye's syndrome : Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness. Allergy alert : Aspirin may cause a severe allergic reaction, which may include: hives facial swelling shock asthma (wheezing) Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you: are age 60 or older have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] have 3 or more alcoholic drinks every day while using this product take more or for a longer time than directed Do not use if you are allergic to aspirin or any other pain reliever/f",
  'active_ingredient': 'Active ingredient (in each tablet) Aspirin 81 mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': '55f373b7-0c70-b19c-e063-6294a90a82d2',
  'brand_name': 'Rapidol Aspirin',
  'generic_name': 'ASPIRIN',
  'manufacturer': 'Pharmadel LLC',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ASPIRIN'],
  'ndc': ['55758-363'],
  'effective_time': '20260706',
  'purpose': 'Active ingredient (in each tablet) Purpose Aspirin 325 mg (NSAID*) ............................. *nonsteroidal anti-inﬂammatory drug Pain reliever',
  'indications_and_usage': 'Uses Temporary relief of minor aches and pains due to: a cold headache backache muscular aches toothache minor pains from arthritis',
  'warnings': "Warnings Reye's syndrome: Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness. Allergy alert: Aspirin may cause severe allergic reactions which may include: ■ hives ■ facial swelling ■ shock ■ asthma (wheezing) Stomach bleeding warning: This product contains an NSAID , which may cause severe stomach bleeding. The chance is higher if you: ■ are age 60 or older ■ have had stomach ulcers or bleeding problems ■ take a blood thinning (anticoagulant) or steroid drug ■ take other drugs containing prescription or nonprescription NSAIDs (aspirin, ibuproben, naproxen, or others) ■ have 3 or more alcoholic drinks every day while using this product ■ take more or for a longer time than directed Do not use ■ if you have ever had an allergic reactio",
  'active_ingredient': 'Active ingredient and Purpose . Active ingredient (in each tablet) Purpose Aspirin 325 mg (NSAID*) ............................. *nonsteroidal anti-inﬂammatory drug Pain reliever'},
 {'id': '385229c2-9b6a-56ca-e063-6394a90aa5b7',
  'brand_name': 'Aspirin Low Dose',
  'generic_name': 'ASPIRIN',
  'manufacturer': 'ATLANTIC BIOLOGICALS CORP.',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ASPIRIN'],
  'ndc': ['17856-3086'],
  'effective_time': '20250624',
  'purpose': 'Purpose Pain reliever',
  'indications_and_usage': 'Uses for the temporary relief of minor aches and pains or as recommended by your doctor. Because of its delayed action, this product will not provide fast relief of headaches or other symptoms needing immediate relief.',
  'warnings': "Warnings Reye's syndrome: Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness. Allergy alert: Aspirin may cause a severe allergic reaction, which may include: hives facial swelling shock asthma (wheezing) Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you take more or for a longer time than directed take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug are age 60 or older have 3 or more alcoholic drinks every day while using this product Do not use if you are allergic to aspirin or any other pain reliever/feve",
  'active_ingredient': 'Active ingredient (in each tablet) Aspirin 81 mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': '7d78e8c1-f247-413e-aa4b-c07d1ef583d0',
  'brand_name': 'GOODYS MAX',
  'generic_name': 'ACETAMINOPHEN, ASPIRIN, AND CAFFEINE',
  'manufacturer': 'Medtech Products Inc.',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ACETAMINOPHEN', 'ASPIRIN', 'CAFFEINE'],
  'ndc': ['63029-668'],
  'effective_time': '20260202',
  'purpose': 'Purpose Pain reliever Pain reliever Pain reliever aid',
  'indications_and_usage': 'Uses Temporarily relieves minor aches and pains due to: headache minor arthritis pain a cold backaches toothache muscular aches menstrual cramps',
  'warnings': 'Warnings Reye’s syndrome: Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye’s syndrome, a rare but serious illness. Allergy alert: Aspirin may cause severe allergic reaction which may include: hives facial swelling asthma (wheezing) shock. Acetaminophen may cause severe skin reactions. Symptoms may include: skin reddening blisters rash. If a skin reaction occurs, stop use and seek medical help right away. Liver warning: This product contains acetaminophen. Severe liver damage may occur if you take more than 4 packs in 24 hours, which is the maximum daily amount with other drugs containing acetaminophen 3 or more alcoholic drinks every day while using this product Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance ',
  'active_ingredient': 'Active ingredient s ( i n each powder ) Acetaminophen 500 mg Aspirin (NSAID*) 500 mg Caffeine 130 mg *nonsteroidal anti-inflammatory drug'},
 {'id': '596aa89c-cc19-7c35-e063-6394a90a5f5c',
  'brand_name': 'CARDIASPIRIN PROTECT',
  'generic_name': 'ASPIRIN',
  'manufacturer': 'OPMX LLC',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ASPIRIN'],
  'ndc': ['69729-104'],
  'effective_time': '20260819',
  'purpose': 'Purpose Active ingredient (in each tablet) Purpose Aspirin 81mg (NSAID)* Pain reliever *nonsteroidal ant-inflammatory drug',
  'indications_and_usage': 'Uses ftemporarily relief of minor aches and pains or as recommended by your doctor. Because of its delayed release action, this product will not provide fast relief of headache or symptoms needing immediate relief.',
  'warnings': "Warnings Reye's syndrome: Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness. Allergy alert: Aspirin may cause a severe allergic reaction which may include: hives shock facial swelling asthma (wheezing) Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you: are age 60 or older have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug take other drugs containing prescription or nonprescription NSAIDs (aspirin, ibuprofen, naproxen, or others) have 3 or more alcoholic drinks every day while using this product take more or for a longer time than directed Do not use if you are allergic to aspirin or any other pain reliever/feve",
  'active_ingredient': 'Active ingredient (in each tablet) Aspirin 81 mg (NSAID) nonsteroidal anti-inflammatory drug Purpose Active ingredient (in each tablet) Purpose Aspirin 81mg (NSAID)* Pain reliever *nonsteroidal ant-inflammatory drug'},
 {'id': '285f424d-b50c-c734-e063-6394a90a9680',
  'brand_name': 'HEB Effervescent Pain Relief',
  'generic_name': 'ASPIRIN',
  'manufacturer': 'H. E. BUTT GROCERY COMPANY',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ASPIRIN'],
  'ndc': ['37808-861'],
  'effective_time': '20241203',
  'purpose': 'Purpose (in each effervescent tablet) Buffered aspirin 325 mg (NSAID)* . . . . . . . . . . Pain reliever/fever reducer *Nonsteroidal anti-inflammatory drug',
  'indications_and_usage': 'Uses ■ for the temporary relief of minor aches and pains due to: ■ headache ■ muscle pain ■ backache ■ toothache ■ menstrual pain ■ colds ■ minor arthritis pain ■ temporarily reduces fever',
  'warnings': 'Warnings Reye’s syndrome: Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye’s syndrome, a rare but serious illness. Allergy alert: Aspirin may cause a severe allergic reaction which may include: ■ hives ■ facial swelling ■ asthma (wheezing) ■ shock Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you ■ are age 60 or older ■ have had stomach ulcers or bleeding problems ■ take a blood thinning (anticoagulant) or steroid drug ■ take other drugs containing prescription or nonprescription NSAIDs (aspirin, ibuprofen, naproxen, or others) ■ have 3 or more alcoholic drinks every day while using this product ■ take more or for a longer time than directed',
  'active_ingredient': 'Active ingredient (in each effervescent tablet) Buffered aspirin 325 mg (NSAID)* *Nonsteroidal anti-inflammatory drug'},
 {'id': '249d869c-d17e-ebcb-e063-6394a90a94b6',
  'brand_name': 'Enteric Coated Aspirin',
  'generic_name': 'ASPIRIN',
  'manufacturer': 'DISCOUNT DRUG MART',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ASPIRIN'],
  'ndc': ['53943-081'],
  'effective_time': '20241016',
  'purpose': 'Purpose Pain reliever',
  'indications_and_usage': 'Uses for the temporary relief of minor aches and pains due to: headache muscle pain toothache menstrual pain colds minor pain of arthritis or as recommended by your doctor',
  'warnings': "Warnings Reye's syndrome Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness. Allergy alert Aspirin may cause a severe allergic reaction which may include: hives facial swelling shock asthma (wheezing) Stomach bleeding warning This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you: are age 60 or older have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug take other drugs containing prescription or nonprescription NSAIDs (aspirin, ibuprofen, naproxen, or others) have 3 more alcoholic drinks every day while using this product take more or for a longer time than directed Do not use if you have ever had an allergic reaction to any other pain reliever",
  'active_ingredient': 'Active ingredient (in each tablet) Aspirin 325 mg (NSAID nonsteroidal anti-inflammatory drug )'},
 {'id': 'c8032d71-2485-4ab4-a20f-153fc3dc6281',
  'brand_name': 'Aspirin Enteric Coated',
  'generic_name': 'ASPIRIN 81 MG',
  'manufacturer': 'Lodaat LLC',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ASPIRIN'],
  'ndc': ['83139-372'],
  'effective_time': '20230131',
  'purpose': 'Purpose Pain reliever',
  'indications_and_usage': 'Use(s) for the temporary relief of minor aches and pain or as recommended by your doctor. Because of its delayed action, this product will not provide fast relief of headaches or other symptoms needing immediate relief.',
  'warnings': 'Warnings Reye’s syndrome: Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye’s syndrome, a rare but serious illness. Allergy alert : Aspirin may cause a severe allergic reaction which may include: hives facial swelling asthma (wheezing) shock Stomach bleeding warning: This product contains an NSAID which may cause severe stomach bleeding. The chance is higher if you: are age 60 or older have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug take other drugs containing prescription or non prescription NSAIDs (aspirin, ibuprofen, naproxen, or others) have 3 or more alcoholic drinks every day while using this product take more or for a longer time than directed Do not use if you are allergic to aspirin or any other pain reliever/fev',
  'active_ingredient': 'Active ingredient(s) Aspirin 81mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': '2969de2e-dde5-8daa-e063-6394a90a5009',
  'brand_name': 'Extra Strength Headache, Caseys 4good',
  'generic_name': 'ACETAMINOPHEN, ASPIRIN, CAFFEINE TABLET',
  'manufacturer': "Lil' Drug Store Products, Inc.",
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['CAFFEINE', 'ACETAMINOPHEN', 'ASPIRIN'],
  'ndc': ['66715-6338'],
  'effective_time': '20241216',
  'purpose': 'Purpose \u200bPurposes Pain reliever Pain reliever Pain reliever aid',
  'indications_and_usage': 'Uses Uses temporarily relieves minor aches and pains due to: headache a cold arthritis muscular aches toothache premenstrual & menstrual cramps',
  'warnings': "Warnings \u200bWarnings Reye’s syndrome Reye’s syndrome: Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness. Allergy alert: Acetaminophen Allergy alert: Acetaminophen may cause severe skin reactions. Symptoms may include: skin reddening blisters rash If a skin reaction occurs, stop use and seek medical help right away. Allergy alert: Aspirin Allergy alert: Aspirin (NSAIDs) may cause a severe allergic reaction which may include: hives facial swelling asthma (wheezing) shock Liver warning Liver warning: This product contains acetaminophen. Severe liver damage may occur if you take: more than 8 caplets in 24 hours, which is the maximum daily amount with other drugs containing acetaminophen 3 or more alcoholic drinks every day while using this",
  'active_ingredient': 'Active ingredients Active ingredients (in each caplet) Acetaminophen 250 mg Aspirin ( NSAID *) 250 mg Caffeine 65 mg *nonsteroidal anti-inflammatory drug'},
 {'id': '45b0b233-b206-0519-e063-6394a90aab06',
  'brand_name': 'Aspirin 81 MG',
  'generic_name': 'ASPIRIN',
  'manufacturer': 'VALU MERCHANDISERS COMPANY',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['ASPIRIN'],
  'ndc': ['63941-080'],
  'effective_time': '20251211',
  'purpose': 'Purpose Pain reliever',
  'indications_and_usage': 'Uses for the temporary relief of minor aches and pains or as recommended by your doctor. Because of its delayed action, this product will not provide fast relief of headaches or other symptoms needing immediate relief. ask your doctor about other uses for this product',
  'warnings': "Warnings Reye's syndrome Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye’s syndrome, a rare but serious illness. Allergy alert Aspirin may cause a severe allergic reaction which may include: hives facial swelling asthma (wheezing) shock Stomach bleeding warning This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you: are age 60 or older have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug take other drugs containing prescription or nonprescription NSAIDs (aspirin, ibuprofen, naproxen, or others) have 3 or more alcoholic drinks every day while using this product take more or for a longer time than directed Do not use if you are allergic to aspirin or any other pain reliever/fever r",
  'active_ingredient': 'Active ingredient (in each tablet) Aspirin 81 mg (NSAID)* * nonsteroidal anti-inflammatory drug'}]

In [49]:
data = response.json()

In [51]:
type(data)

list

In [53]:
len(data)

10

In [55]:
data[0]

{'id': '008ee85b-5cac-45a6-a857-a828f8125175',
 'brand_name': 'Low Dose Aspirin',
 'generic_name': 'ASPIRIN',
 'manufacturer': 'P & L Development, LLC',
 'route': ['ORAL'],
 'dosage_form': None,
 'product_type': 'HUMAN OTC DRUG',
 'substance_name': ['ASPIRIN'],
 'ndc': ['59726-065'],
 'effective_time': '20240416',
 'purpose': 'Purpose Pain reliever',
 'indications_and_usage': 'Uses for the temporary relief of minor aches and pains or as recommended by your doctor. Because of its delayed action, this product will not provide fast relief of headaches or other symptoms needing immediate relief. ask your doctor about other uses for safety coated 81 mg aspirin',
 'warnings': "Warnings Reye's syndrome : Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness. Allergy alert : Aspirin may cause a severe allergic reaction, which may include: hives facial swelling shock asthma (wheezing) Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you: are age 60 or older have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] have 3 or more alcoholic drinks every day while using this product take more or for a longer time than directed Do not use if you are allergic to aspirin or any other pain reliever/f",
 'active_ingredient': 'Active ingredient (in each tablet) Aspirin 81 mg (NSAID)* *nonsteroidal anti-inflammatory drug'}

In [57]:
type(data[0])

dict

In [59]:
data[0]["brand_name"]

'Low Dose Aspirin'

In [61]:
data[0]["active_ingredient"]

'Active ingredient (in each tablet) Aspirin 81 mg (NSAID)* *nonsteroidal anti-inflammatory drug'

In [63]:
data[0]["substance_name"]

['ASPIRIN']

In [65]:
type(data[0]["substance_name"])

list

In [67]:
data[3]["brand_name"]

'GOODYS MAX'

In [69]:
data[3]["substance_name"]

['ACETAMINOPHEN', 'ASPIRIN', 'CAFFEINE']

In [71]:
def search_medication_api(medication_name):
    """
    Search the external medication API using a medication name.

    Parameters:
        medication_name (str): The medication name entered by the user.

    Returns:
        list: Medication records returned by the API.
    """

    url = "https://drug-information-api-fda-labels-and-ndc-lookup.p.rapidapi.com/drugs/search"
    querystring = {"limit": "10","q": medication_name}
    headers = {"x-rapidapi-key": rapidapi_key,"x-rapidapi-host": "drug-information-api-fda-labels-and-ndc-lookup.p.rapidapi.com","Content-Type": "application/json"}
    response = requests.get(url, headers=headers, params=querystring)

    if response.status_code == 200:
        return response.json()
    else:
        print("API request failed. Status code:", response.status_code)
        print('API response',response.text)
        return []

In [73]:
test_results = search_medication_api('ibruprofen')

API request failed. Status code: 404
API response {"error":"NOT_FOUND","message":"No record found upstream"}

In [75]:
test_results =search_medication_api('aspirin')

In [77]:
len(test_results)

10

In [79]:
test_results = search_medication_api('ibruprofen')

API request failed. Status code: 404
API response {"error":"NOT_FOUND","message":"No record found upstream"}

In [80]:
test_results = search_medication_api('ibuprofen')
test_results

[{'id': '4bd1345d-d116-426e-825f-bbf29381746a',
  'brand_name': 'Ibuprofen Dye Free',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'CVS Pharmacy',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['59779-438'],
  'effective_time': '20260429',
  'purpose': 'Purpose Pain reliever/fever reducer',
  'indications_and_usage': 'Uses temporarily relieves minor aches and pains due to: headache toothache backache menstrual cramps the common cold muscular aches minor pain of arthritis temporarily reduces fever',
  'warnings': 'Warnings Allergy alert: Ibuprofen may cause a severe allergic reaction, especially in people allergic to aspirin. Symptoms may include: rash facial swelling asthma (wheezing) hives skin reddening shock blisters If an allergic reaction occurs, stop use and seek medical help right away. Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you: take more or for a longer time than directed take a blood thinning (anticoagulant) or steroid drug have had stomach ulcers or bleeding problems have 3 or more alcoholic drinks every day while using this product are age 60 or older take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] Heart attack and stroke warning: NSAIDs, except aspirin, increase the risk of heart attack, heart failure, and stroke. These can be fatal. The risk is higher if you use more than directed or for longer than directed. Do not use if you have ever h',
  'active_ingredient': 'Active ingredient (in each white tablet) Ibuprofen USP, 200 mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': 'ec4746b3-2707-40c5-bb70-58a42f46c249',
  'brand_name': 'care one ibuprofen',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'American Sales Company',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['41520-604'],
  'effective_time': '20250603',
  'purpose': 'Purposes Pain reliever/fever reducer',
  'indications_and_usage': 'Uses • temporarily relieves minor aches and pains due to: • headache • muscular aches • minor pain of arthritis • toothache • backache • the common cold • menstrual cramps • temporarily reduces fever',
  'warnings': 'Warnings Allergy alert: Ibuprofen may cause a severe allergic reaction, especially in people allergic to aspirin. Symptoms may include: • hives • facial swelling • asthma (wheezing) • shock • skin reddening • rash • blisters If an allergic reaction occurs, stop use and seek medical help right away. Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you • are age 60 or older • have had stomach ulcers or bleeding problems • take a blood thinning (anticoagulant) or steroid drug • take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] • have 3 or more alcoholic drinks every day while using this product • take more or for a longer time than directed Heart attack and stroke warning: NSAIDs, except aspirin, increase the risk of heart attack, heart failure, and stroke. These can be fatal. The risk is higher if you use more than directed or for longer than directed. Do n',
  'active_ingredient': 'Active ingredient (in each tablet) Ibuprofen 200 mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': '5e595111-8477-4ec7-8d32-a0aeabc04e1a',
  'brand_name': 'Ibuprofen',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'Aurobindo Pharma Limited',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN PRESCRIPTION DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['59651-360', '59651-361', '59651-362'],
  'effective_time': '20250214',
  'purpose': None,
  'indications_and_usage': 'INDICATIONS AND USAGE Carefully consider the potential benefits and risks of ibuprofen tablets and other treatment options before deciding to use ibuprofen. Use the lowest effective dose for the shortest duration consistent with individual patient treatment goals (see WARNINGS ). Ibuprofen tablets are indicated for relief of the signs and symptoms of rheumatoid arthritis and osteoarthritis. Ibuprofen tablets are indicated for relief of mild to moderate pain. Ibuprofen tablets are also indicated for the treatment of primary dysmenorrhea. Controlled clinical trials to establish the safety and effectiveness of ibuprofen tablets in children have not been conducted.',
  'warnings': 'WARNINGS Cardiovascular Effects Cardiovascular Thrombotic Events Clinical trials of several COX-2 selective and nonselective NSAIDs of up to three years duration have shown an increased risk of serious cardiovascular (CV) thrombotic events, including myocardial infarction (MI) and stroke, which can be fatal. Based on available data, it is unclear that the risk for CV thrombotic events is similar for all NSAIDs. The relative increase in serious CV thrombotic events over baseline conferred by NSAID use appears to be similar in those with and without known CV disease or risk factors for CV disease. However, patients with known CV disease or risk factors had a higher absolute incidence of excess serious CV thrombotic events, due to their increased baseline rate. Some observational studies found that this increased risk of serious CV thrombotic events began as early as the first weeks of treatment. The increase in CV thrombotic risk has been observed most consistently at higher doses. To mi',
  'active_ingredient': None},
 {'id': 'b245c1c7-1add-4087-8ae8-ff5b3f46183d',
  'brand_name': 'leader Ibuprofen',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'Cardinal Health 110, LLC. dba Leader',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['70000-0264'],
  'effective_time': '20250626',
  'purpose': 'Purposes Pain reliever/fever reducer',
  'indications_and_usage': 'Uses temporarily: • relieves minor aches and pains due to the common cold, flu, sore throat, headache and toothache • reduces fever',
  'warnings': 'Warnings Allergy alert: Ibuprofen may cause a severe allergic reaction, especially in people allergic to aspirin. Symptoms may include: • hives • facial swelling • asthma (wheezing) • shock • skin reddening • rash • blisters If an allergic reaction occurs, stop use and seek medical help right away. Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if your child: • has had stomach ulcers or bleeding problems • takes a blood thinning (anticoagulant) or steroid drug • takes other drugs containing prescription or nonprescription NSAIDs (aspirin, ibuprofen, naproxen, or others) • takes more or for a longer time than directed Heart attack and stroke warning: NSAIDs, except aspirin, increase the risk of heart attack, heart failure, and stroke. These can be fatal. The risk is higher if you use more than directed or for longer than directed. Sore throat warning: Severe or persistent sore throat or sore throat accompanied by h',
  'active_ingredient': 'Active ingredient (in each 5 mL) Ibuprofen 100 mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': 'ad449225-ed60-4c66-9fd6-34bef9a4b42e',
  'brand_name': 'Concentrated ibuprofen infants',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'Wal-Mart Stores, Inc.',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['49035-635'],
  'effective_time': '20220111',
  'purpose': 'PURPOSE Pain reliever/fever reducer',
  'indications_and_usage': 'USE(S) temporarily: reduces fever relieves minor aches and pains due to the common cold, flu, sore throat, headaches and toothaches',
  'warnings': 'WARNINGS Allergy alert: Ibuprofen may cause a severe allergic reaction, especially in people allergic to aspirin. Symptoms may include: hives facial swelling asthma (wheezing) shock skin reddening rash blisters If an allergic reaction occurs, stop use and seek medical help right away. Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you child: has had stomach ulcers or bleeding problems takes a blood thinning (anticoagulant) or steroid drug takes other drugs containing prescription or nonprescription NSAIDs (aspirin, ibuprofen, naproxen, or others) takes more or for a longer time than directed Heart attack and stroke warning: NSAIDs, except aspirin, increase the risk of heart attack, heart failure and stroke. These can be fatal. The risk is higher if you use more than directed or for longer than directed. Sore throat warning: Severe or persistent sore throat or sore throat accompanied by high fever, headache, nau',
  'active_ingredient': 'ACTIVE INGREDIENT (in each 1.25 mL) Ibuprofen 50 mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': 'f581be63-9628-433f-8a31-eba6f530254e',
  'brand_name': 'Topcare Infants Ibuprofen',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'Topco Associates LLC',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['36800-057'],
  'effective_time': '20250503',
  'purpose': 'Purposes Pain reliever/fever reducer',
  'indications_and_usage': 'Uses temporarily: • reduces fever • relieves minor aches and pains due to the common cold, flu, sore throat, headaches and toothaches',
  'warnings': 'Warnings Allergy alert: Ibuprofen may cause a severe allergic reaction, especially in people allergic to aspirin. Symptoms may include: • hives • facial swelling • asthma (wheezing) • shock • skin reddening • rash • blisters If an allergic reaction occurs, stop use and seek medical help right away. Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if your child: • has had stomach ulcers or bleeding problems • takes a blood thinning (anticoagulant) or steroid drug • takes other drugs containing prescription or nonprescription NSAIDs (aspirin, ibuprofen, naproxen, or others) • takes more or for a longer time than directed Heart attack and stroke warning: NSAIDs, except aspirin, increase the risk of heart attack, heart failure, and stroke. These can be fatal. The risk is higher if you use more than directed or for longer than directed. Sore throat warning: Severe or persistent sore throat or sore throat accompanied by h',
  'active_ingredient': 'Active ingredient (in each 1.25 mL) Ibuprofen 50 mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': '2790ee9d-7db5-427c-ad2b-394dfaa55f9f',
  'brand_name': 'Ibuprofen',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'Care One (American Sales Company)',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['41520-745'],
  'effective_time': '20221121',
  'purpose': 'Purpose Pain reliever/fever reducer',
  'indications_and_usage': 'Uses temporarily relieves minor aches and pains due to: headache muscular aches minor pain of arthritis toothache backache the common cold menstrual cramps temporarily reduces fever',
  'warnings': 'Warnings Allergy alert : Ibuprofen may cause a severe allergic reaction, especially in people allergic to aspirin. Symptoms may include: hives facial swelling asthma (wheezing) shock skin reddening rash blisters If an allergic reaction occurs, stop use and seek medical help right away. Stomach bleeding warning : This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you: are age 60 or older have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] have 3 or more alcoholic drinks every day while using this product take more or for a longer time than directed Heart attack and stroke warning: NSAIDs, except aspirin, increase the risk of heart attack, heart failure, and stroke.These can be fatal. The risk is higher if you use more than directed or for longer than directed. Do not use if you have ever ',
  'active_ingredient': 'Active ingredient (in each capsule) Solubilized ibuprofen equal to 200 mg ibuprofen (NSAID)* (present as the free acid and potassium salt) *nonsteroidal anti-inflammatory drug'},
 {'id': '56fb8ceb-3a90-44df-881b-9d93606bbac6',
  'brand_name': 'Ibuprofen',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'A-S Medication Solutions',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN PRESCRIPTION DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['50090-7905'],
  'effective_time': '20260217',
  'purpose': None,
  'indications_and_usage': 'INDICATIONS AND USAGE Carefully consider the potential benefits and risks of Ibuprofen tablets and other treatment options before deciding to use ibuprofen. Use the lowest effective dose for the shortest duration consistent with individual patient treatment goals [see WARNINGS ]. Ibuprofen tablets are indicated for relief of the signs and symptoms of rheumatoid arthritis and osteoarthritis. Ibuprofen tablets are indicated for relief of mild to moderate pain. Ibuprofen tablets are also indicated for the treatment of primary dysmenorrhea. Controlled clinical trials to establish the safety and effectiveness of Ibuprofen tablets in children have not been conducted.',
  'warnings': 'WARNINGS CARDIOVASCULAR EFFECTS Cardiovascular Thrombotic Events Clinical trials of several COX-2 selective and nonselective NSAIDs of up to three years duration have shown an increased risk of serious cardiovascular (CV) thrombotic events, including myocardial infarction (MI) and stroke, which can be fatal. Based on available data, it is unclear that the risk for CV thrombotic events is similar for all NSAIDs. The relative increase in serious CV thrombotic events over baseline conferred by NSAID use appears to be similar in those with and without known CV disease or risk factors for CV disease. However, Patients with known CV disease or risk factors had a higher absolute incidence of excess serious CV thrombotic events, due to their increased baseline rate. Some observational studies found that this increased risk of serious CV thrombotic events began as early as the first weeks of treatment. The increase in CV thrombotic risk has been observed most consistently at higher doses. To mi',
  'active_ingredient': None},
 {'id': '30efa597-b7ea-4db5-8988-64e04667232b',
  'brand_name': 'Equate Ibuprofen',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'Wal-Mart Stores Inc',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['49035-553'],
  'effective_time': '20250211',
  'purpose': 'Purposes Pain reliever/fever reducer',
  'indications_and_usage': 'Uses • temporarily relieves minor aches and pains due to: • headache • muscular aches • minor pain of arthritis • toothache • backache • the common cold • menstrual cramps • temporarily reduces fever',
  'warnings': 'Warnings Allergy alert: Ibuprofen may cause a severe allergic reaction, especially in people allergic to aspirin. Symptoms may include: • hives • facial swelling • asthma (wheezing) • shock • skin reddening • rash • blisters If an allergic reaction occurs, stop use and seek medical help right away. Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chances are higher if you • are age 60 or older • have had stomach ulcers or bleeding problems • take a blood thinning (anticoagulant) or steroid drug • take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] • have 3 or more alcoholic drinks every day while using this product • take more or for a longer time than directed Heart attack and stroke warning: NSAIDs, except aspirin, increase the risk of heart attack, heart failure, and stroke. These can be fatal. The risk is higher if you use more than directed or for longer than directed. Do',
  'active_ingredient': 'Active ingredient (in each tablet) Ibuprofen 200 mg (NSAID)* *nonsteroidal anti-inflammatory drug'},
 {'id': 'f1932057-8d9f-4b59-9c49-d7d4c7251352',
  'brand_name': 'Ibuprofen',
  'generic_name': 'IBUPROFEN',
  'manufacturer': 'ARMY AND AIR FORCE EXCHANGE SERVICE',
  'route': ['ORAL'],
  'dosage_form': None,
  'product_type': 'HUMAN OTC DRUG',
  'substance_name': ['IBUPROFEN'],
  'ndc': ['55301-393'],
  'effective_time': '20260615',
  'purpose': 'Purpose Pain reliever/fever reducer',
  'indications_and_usage': 'Uses temporarily relieves minor aches and pains due to: menstrual cramps toothache the common cold backache headache muscular aches minor pain of arthritis temporarily reduces fever',
  'warnings': 'Warnings Allergy alert: Ibuprofen may cause a severe allergic reaction, especially in people allergic to aspirin. Symptoms may include: skin reddening asthma (wheezing) rash facial swelling shock blisters hives If an allergic reaction occurs, stop use and seek medical help right away. Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you take more or for a longer time than directed take a blood thinning (anticoagulant) or steroid drug are age 60 or older take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] have had stomach ulcers or bleeding problems have 3 or more alcoholic drinks every day while using this product Heart attack and stroke warning: NSAIDs, except aspirin, increase the risk of heart attack, heart failure, and stroke. These can be fatal. The risk is higher if you use more than directed or for longer than directed. Do not use if you have ever ha',
  'active_ingredient': 'Active ingredient (in each orange caplet) Ibuprofen USP, 200 mg (NSAID)* *nonsteroidal anti-inflammatory drug'}]

In [82]:
len(test_results)

10

# LLM API integration

In [86]:
open_router_key = getpass.getpass('Enter your OpenRouter API key:')

Enter your OpenRouter API key: ········

In [94]:
with open('.env','a') as file:
    file.write(f"\n OPENROUTER_API_KEY={open_router_key}")

In [96]:
load_dotenv()

True

In [98]:
openrouter_key = os.getenv('OPENROUTER_API_KEY')

In [100]:
llm_url = "https://openrouter.ai/api/v1/chat/completions"

In [102]:
llm_headers ={"Authorization": f"Bearer {openrouter_key}","Content-Type": "application/json"}

In [104]:
llm_payload = {"model":'openrouter/free','messages':[{'role':'user','content': 'Explain in simple language what an active ingredient in a medication means.'}]}

In [106]:
load_dotenv(override=True)

True

In [108]:
openrouter_key is not None

True

In [110]:
llm_response = requests.post(llm_url,headers=llm_headers,json=llm_payload)

In [112]:
llm_response

In [114]:
llm_response.text

'\n         \n\n         \n\n         \n\n         \n\n         \n\n         \n\n         \n{"id":"gen-1789945481-YzSdUqr6LZH5fZR7bOAU","object":"chat.completion","created":1789945481,"model":"poolside/laguna-s-2.1:free","provider":"Poolside","system_fingerprint":null,"service_tier":null,"choices":[{"index":0,"logprobs":null,"finish_reason":"stop","native_finish_reason":"stop","message":{"role":"assistant","content":"The **active ingredient** in a medication is the main part that **actually treats your health condition**. Think of it like the \\"star player\\" on a team—it’s the component that fights your symptoms or illness. For example, in a pain reliever like ibuprofen (found in Advil or Motrin), the active ingredient is ibuprofen itself, which reduces pain and inflammation.\\n\\n### What about the other stuff?\\nMedications also contain **inactive ingredients**. These act like helpers—they might make the pill easier to swallow, help it dissolve properly, add color, or preserve it. They *don’t* treat your condition; they just help the active ingredient work better.\\n\\n### Why does it matter?\\n- **Know what you’re taking**: The active ingredient is listed on medicine labels, so you can spot allergies, avoid duplicates (like taking two medicines with the same active ingredient), or choose a generic brand (which often has the same active ingredient as a more expensive brand name).\\n- **Examples**:  \\n  - In **Lipitor** (a cholesterol drug), the active ingredient is **atorvastatin**.  \\n  - In **Zyrtec** (an allergy pill), it’s **loratadine**.  \\n\\n### Simple takeaway:\\nThe active ingredient is the key \\"doer\\" in your medicine. Everything else is there to help it work, taste better, or look nice on the shelf. Always check the label to know what’s inside!","refusal":null,"reasoning":"Okay, I need to explain what an active ingredient in medication means in simple terms. Let me start by recalling what I know. Medication usually has multiple components, right? The active ingredient is the part that actually does something to treat the condition. But I should make sure I\'m accurate.\\n\\nWait, so when you take a pill, the active ingredient is the part that\'s responsible for the effect. The rest are probably fillers or something to help the pill hold together. Like, maybe other substances help it dissolve properly or taste better. So the active ingredient is the actual drug that works on the body.\\n\\nI should mention that the active ingredient is the one that affects the body\'s process or targets a specific problem. For example, in pain relievers, maybe something like ibuprofen is the active ingredient. It reduces inflammation and pain. The other parts don\'t do much in terms of the effect, just help with delivery.\\n\\nOh, right, the FDA or other agencies require the active ingredient to be listed on the label. That\'s important for people with allergies or to avoid duplicates. So when reading a label, the active ingredient section tells you exactly what\'s in there that\'s making it work.\\n\\nAlso, different medications might have the same active ingredient but different brand names. Like acetaminophen can be found in Tylenol or other brands. That\'s why knowing the active ingredient is key when comparing medications.\\n\\nWait, are there examples I can use? Maybe aspirin, which has acetylsalicylic acid as the active ingredient. Or antihistamines for allergies, like loratadine. That\'s the part that makes it work, the rest are just to make it easier to take, maybe a coating or dyes.\\n\\nHmm, maybe I should structure it as: definition, role, contrast with inactive ingredients, why it\'s important to know, and examples. That way it covers all bases without getting too technical. Need to make sure the language is simple, avoiding jargon. So instead of \\"pharmacologically active,\\" just say \\"the part that actually treats the condition.\\"\\n\\nAlso, maybe mention that it\'s listed by its scientific or generic name. People might not recognize it, so that\'s why it\'s on the label. So even if two products are different brands, if the active ingredient is the same, they work the same way.\\n\\nLet me check if I have all points. Active ingredient is the key component that does the work, inactive are the others that help with delivery, necessity of labeling, examples. Yeah, that should cover it. I should avoid any complex explanations. Keep it conversational. Maybe start with an analogy? Like how in a recipe, the main ingredient that gives the dish its flavor is the active part, while others help in making it. Not sure if that\'s necessary, but simple analogies can help.\\n\\nAlso, make sure to clarify that the inactive ingredients don\'t contribute to the treatment, but they don\'t cause harm. They help with things like stability, absorption, etc. So together, active and inactive make up the whole drug. Maybe use a vitamin pill as an example, where the vitamin is the active ingredient and the rest are binders or coatings.\\n\\nOkay, putting it all together. Start by saying the active ingredient is the main part that treats the condition. Then contrast with inactive ones. Explain why it\'s important (labels, allergies, etc.). Use examples to make it clear. Keep sentences short and use easy words. Avoid saying \\"pharmacologically active\\" or terms that might not be familiar. Let me see if I missed anything. Maybe mention that it\'s different in each medication, so each has its own active ingredient(s) depending on what they\'re for. Like antibiotics vs. pain relievers have different actives targeting different issues.","reasoning_details":[{"type":"reasoning.text","text":"Okay, I need to explain what an active ingredient in medication means in simple terms. Let me start by recalling what I know. Medication usually has multiple components, right? The active ingredient is the part that actually does something to treat the condition. But I should make sure I\'m accurate.\\n\\nWait, so when you take a pill, the active ingredient is the part that\'s responsible for the effect. The rest are probably fillers or something to help the pill hold together. Like, maybe other substances help it dissolve properly or taste better. So the active ingredient is the actual drug that works on the body.\\n\\nI should mention that the active ingredient is the one that affects the body\'s process or targets a specific problem. For example, in pain relievers, maybe something like ibuprofen is the active ingredient. It reduces inflammation and pain. The other parts don\'t do much in terms of the effect, just help with delivery.\\n\\nOh, right, the FDA or other agencies require the active ingredient to be listed on the label. That\'s important for people with allergies or to avoid duplicates. So when reading a label, the active ingredient section tells you exactly what\'s in there that\'s making it work.\\n\\nAlso, different medications might have the same active ingredient but different brand names. Like acetaminophen can be found in Tylenol or other brands. That\'s why knowing the active ingredient is key when comparing medications.\\n\\nWait, are there examples I can use? Maybe aspirin, which has acetylsalicylic acid as the active ingredient. Or antihistamines for allergies, like loratadine. That\'s the part that makes it work, the rest are just to make it easier to take, maybe a coating or dyes.\\n\\nHmm, maybe I should structure it as: definition, role, contrast with inactive ingredients, why it\'s important to know, and examples. That way it covers all bases without getting too technical. Need to make sure the language is simple, avoiding jargon. So instead of \\"pharmacologically active,\\" just say \\"the part that actually treats the condition.\\"\\n\\nAlso, maybe mention that it\'s listed by its scientific or generic name. People might not recognize it, so that\'s why it\'s on the label. So even if two products are different brands, if the active ingredient is the same, they work the same way.\\n\\nLet me check if I have all points. Active ingredient is the key component that does the work, inactive are the others that help with delivery, necessity of labeling, examples. Yeah, that should cover it. I should avoid any complex explanations. Keep it conversational. Maybe start with an analogy? Like how in a recipe, the main ingredient that gives the dish its flavor is the active part, while others help in making it. Not sure if that\'s necessary, but simple analogies can help.\\n\\nAlso, make sure to clarify that the inactive ingredients don\'t contribute to the treatment, but they don\'t cause harm. They help with things like stability, absorption, etc. So together, active and inactive make up the whole drug. Maybe use a vitamin pill as an example, where the vitamin is the active ingredient and the rest are binders or coatings.\\n\\nOkay, putting it all together. Start by saying the active ingredient is the main part that treats the condition. Then contrast with inactive ones. Explain why it\'s important (labels, allergies, etc.). Use examples to make it clear. Keep sentences short and use easy words. Avoid saying \\"pharmacologically active\\" or terms that might not be familiar. Let me see if I missed anything. Maybe mention that it\'s different in each medication, so each has its own active ingredient(s) depending on what they\'re for. Like antibiotics vs. pain relievers have different actives targeting different issues.","format":"unknown","index":0}]}}],"usage":{"prompt_tokens":56,"completion_tokens":1099,"total_tokens":1155,"cost":0,"is_byok":false,"prompt_tokens_details":{"cached_tokens":32,"cache_write_tokens":0,"audio_tokens":0,"video_tokens":0},"cost_details":{"upstream_inference_cost":0,"upstream_inference_prompt_cost":0,"upstream_inference_completions_cost":0},"completion_tokens_details":{"reasoning_tokens":789,"image_tokens":0,"audio_tokens":0}}}'

In [116]:
"Authorization" in llm_response.request.headers

True

In [118]:
from dotenv import dotenv_values

In [120]:
env_values = dotenv_values(".env")

In [122]:
env_values.keys()

odict_keys(['RAPIDAPI_KEY', 'OPENROUTER_API_KEY'])

In [124]:
openrouter_key is not None

True

In [126]:
len(openrouter_key)

73

In [128]:
openrouter_key.startswith("sk-or-v1-c")

True

In [130]:
llm_data = llm_response.json()

In [132]:
type(llm_data)

dict

In [134]:
llm_data.keys()

dict_keys(['id', 'object', 'created', 'model', 'provider', 'system_fingerprint', 'service_tier', 'choices', 'usage'])

In [136]:
llm_data['choices']

[{'index': 0,
  'logprobs': None,
  'finish_reason': 'stop',
  'native_finish_reason': 'stop',
  'message': {'role': 'assistant',
   'content': 'The **active ingredient** in a medication is the main part that **actually treats your health condition**. Think of it like the "star player" on a team—it’s the component that fights your symptoms or illness. For example, in a pain reliever like ibuprofen (found in Advil or Motrin), the active ingredient is ibuprofen itself, which reduces pain and inflammation.\n\n### What about the other stuff?\nMedications also contain **inactive ingredients**. These act like helpers—they might make the pill easier to swallow, help it dissolve properly, add color, or preserve it. They *don’t* treat your condition; they just help the active ingredient work better.\n\n### Why does it matter?\n- **Know what you’re taking**: The active ingredient is listed on medicine labels, so you can spot allergies, avoid duplicates (like taking two medicines with the same active ingredient), or choose a generic brand (which often has the same active ingredient as a more expensive brand name).\n- **Examples**:  \n  - In **Lipitor** (a cholesterol drug), the active ingredient is **atorvastatin**.  \n  - In **Zyrtec** (an allergy pill), it’s **loratadine**.  \n\n### Simple takeaway:\nThe active ingredient is the key "doer" in your medicine. Everything else is there to help it work, taste better, or look nice on the shelf. Always check the label to know what’s inside!',
   'refusal': None,
   'reasoning': 'Okay, I need to explain what an active ingredient in medication means in simple terms. Let me start by recalling what I know. Medication usually has multiple components, right? The active ingredient is the part that actually does something to treat the condition. But I should make sure I\'m accurate.\n\nWait, so when you take a pill, the active ingredient is the part that\'s responsible for the effect. The rest are probably fillers or something to help the pill hold together. Like, maybe other substances help it dissolve properly or taste better. So the active ingredient is the actual drug that works on the body.\n\nI should mention that the active ingredient is the one that affects the body\'s process or targets a specific problem. For example, in pain relievers, maybe something like ibuprofen is the active ingredient. It reduces inflammation and pain. The other parts don\'t do much in terms of the effect, just help with delivery.\n\nOh, right, the FDA or other agencies require the active ingredient to be listed on the label. That\'s important for people with allergies or to avoid duplicates. So when reading a label, the active ingredient section tells you exactly what\'s in there that\'s making it work.\n\nAlso, different medications might have the same active ingredient but different brand names. Like acetaminophen can be found in Tylenol or other brands. That\'s why knowing the active ingredient is key when comparing medications.\n\nWait, are there examples I can use? Maybe aspirin, which has acetylsalicylic acid as the active ingredient. Or antihistamines for allergies, like loratadine. That\'s the part that makes it work, the rest are just to make it easier to take, maybe a coating or dyes.\n\nHmm, maybe I should structure it as: definition, role, contrast with inactive ingredients, why it\'s important to know, and examples. That way it covers all bases without getting too technical. Need to make sure the language is simple, avoiding jargon. So instead of "pharmacologically active," just say "the part that actually treats the condition."\n\nAlso, maybe mention that it\'s listed by its scientific or generic name. People might not recognize it, so that\'s why it\'s on the label. So even if two products are different brands, if the active ingredient is the same, they work the same way.\n\nLet me check if I have all points. Active ingredient is the key component that does the work, inactive are the others that help with delivery, necessity of labeling, examples. Yeah, that should cover it. I should avoid any complex explanations. Keep it conversational. Maybe start with an analogy? Like how in a recipe, the main ingredient that gives the dish its flavor is the active part, while others help in making it. Not sure if that\'s necessary, but simple analogies can help.\n\nAlso, make sure to clarify that the inactive ingredients don\'t contribute to the treatment, but they don\'t cause harm. They help with things like stability, absorption, etc. So together, active and inactive make up the whole drug. Maybe use a vitamin pill as an example, where the vitamin is the active ingredient and the rest are binders or coatings.\n\nOkay, putting it all together. Start by saying the active ingredient is the main part that treats the condition. Then contrast with inactive ones. Explain why it\'s important (labels, allergies, etc.). Use examples to make it clear. Keep sentences short and use easy words. Avoid saying "pharmacologically active" or terms that might not be familiar. Let me see if I missed anything. Maybe mention that it\'s different in each medication, so each has its own active ingredient(s) depending on what they\'re for. Like antibiotics vs. pain relievers have different actives targeting different issues.',
   'reasoning_details': [{'type': 'reasoning.text',
     'text': 'Okay, I need to explain what an active ingredient in medication means in simple terms. Let me start by recalling what I know. Medication usually has multiple components, right? The active ingredient is the part that actually does something to treat the condition. But I should make sure I\'m accurate.\n\nWait, so when you take a pill, the active ingredient is the part that\'s responsible for the effect. The rest are probably fillers or something to help the pill hold together. Like, maybe other substances help it dissolve properly or taste better. So the active ingredient is the actual drug that works on the body.\n\nI should mention that the active ingredient is the one that affects the body\'s process or targets a specific problem. For example, in pain relievers, maybe something like ibuprofen is the active ingredient. It reduces inflammation and pain. The other parts don\'t do much in terms of the effect, just help with delivery.\n\nOh, right, the FDA or other agencies require the active ingredient to be listed on the label. That\'s important for people with allergies or to avoid duplicates. So when reading a label, the active ingredient section tells you exactly what\'s in there that\'s making it work.\n\nAlso, different medications might have the same active ingredient but different brand names. Like acetaminophen can be found in Tylenol or other brands. That\'s why knowing the active ingredient is key when comparing medications.\n\nWait, are there examples I can use? Maybe aspirin, which has acetylsalicylic acid as the active ingredient. Or antihistamines for allergies, like loratadine. That\'s the part that makes it work, the rest are just to make it easier to take, maybe a coating or dyes.\n\nHmm, maybe I should structure it as: definition, role, contrast with inactive ingredients, why it\'s important to know, and examples. That way it covers all bases without getting too technical. Need to make sure the language is simple, avoiding jargon. So instead of "pharmacologically active," just say "the part that actually treats the condition."\n\nAlso, maybe mention that it\'s listed by its scientific or generic name. People might not recognize it, so that\'s why it\'s on the label. So even if two products are different brands, if the active ingredient is the same, they work the same way.\n\nLet me check if I have all points. Active ingredient is the key component that does the work, inactive are the others that help with delivery, necessity of labeling, examples. Yeah, that should cover it. I should avoid any complex explanations. Keep it conversational. Maybe start with an analogy? Like how in a recipe, the main ingredient that gives the dish its flavor is the active part, while others help in making it. Not sure if that\'s necessary, but simple analogies can help.\n\nAlso, make sure to clarify that the inactive ingredients don\'t contribute to the treatment, but they don\'t cause harm. They help with things like stability, absorption, etc. So together, active and inactive make up the whole drug. Maybe use a vitamin pill as an example, where the vitamin is the active ingredient and the rest are binders or coatings.\n\nOkay, putting it all together. Start by saying the active ingredient is the main part that treats the condition. Then contrast with inactive ones. Explain why it\'s important (labels, allergies, etc.). Use examples to make it clear. Keep sentences short and use easy words. Avoid saying "pharmacologically active" or terms that might not be familiar. Let me see if I missed anything. Maybe mention that it\'s different in each medication, so each has its own active ingredient(s) depending on what they\'re for. Like antibiotics vs. pain relievers have different actives targeting different issues.',
     'format': 'unknown',
     'index': 0}]}}]

In [138]:
type(llm_data['choices'])

list

In [140]:
llm_data['choices'][0]

{'index': 0,
 'logprobs': None,
 'finish_reason': 'stop',
 'native_finish_reason': 'stop',
 'message': {'role': 'assistant',
  'content': 'The **active ingredient** in a medication is the main part that **actually treats your health condition**. Think of it like the "star player" on a team—it’s the component that fights your symptoms or illness. For example, in a pain reliever like ibuprofen (found in Advil or Motrin), the active ingredient is ibuprofen itself, which reduces pain and inflammation.\n\n### What about the other stuff?\nMedications also contain **inactive ingredients**. These act like helpers—they might make the pill easier to swallow, help it dissolve properly, add color, or preserve it. They *don’t* treat your condition; they just help the active ingredient work better.\n\n### Why does it matter?\n- **Know what you’re taking**: The active ingredient is listed on medicine labels, so you can spot allergies, avoid duplicates (like taking two medicines with the same active ingredient), or choose a generic brand (which often has the same active ingredient as a more expensive brand name).\n- **Examples**:  \n  - In **Lipitor** (a cholesterol drug), the active ingredient is **atorvastatin**.  \n  - In **Zyrtec** (an allergy pill), it’s **loratadine**.  \n\n### Simple takeaway:\nThe active ingredient is the key "doer" in your medicine. Everything else is there to help it work, taste better, or look nice on the shelf. Always check the label to know what’s inside!',
  'refusal': None,
  'reasoning': 'Okay, I need to explain what an active ingredient in medication means in simple terms. Let me start by recalling what I know. Medication usually has multiple components, right? The active ingredient is the part that actually does something to treat the condition. But I should make sure I\'m accurate.\n\nWait, so when you take a pill, the active ingredient is the part that\'s responsible for the effect. The rest are probably fillers or something to help the pill hold together. Like, maybe other substances help it dissolve properly or taste better. So the active ingredient is the actual drug that works on the body.\n\nI should mention that the active ingredient is the one that affects the body\'s process or targets a specific problem. For example, in pain relievers, maybe something like ibuprofen is the active ingredient. It reduces inflammation and pain. The other parts don\'t do much in terms of the effect, just help with delivery.\n\nOh, right, the FDA or other agencies require the active ingredient to be listed on the label. That\'s important for people with allergies or to avoid duplicates. So when reading a label, the active ingredient section tells you exactly what\'s in there that\'s making it work.\n\nAlso, different medications might have the same active ingredient but different brand names. Like acetaminophen can be found in Tylenol or other brands. That\'s why knowing the active ingredient is key when comparing medications.\n\nWait, are there examples I can use? Maybe aspirin, which has acetylsalicylic acid as the active ingredient. Or antihistamines for allergies, like loratadine. That\'s the part that makes it work, the rest are just to make it easier to take, maybe a coating or dyes.\n\nHmm, maybe I should structure it as: definition, role, contrast with inactive ingredients, why it\'s important to know, and examples. That way it covers all bases without getting too technical. Need to make sure the language is simple, avoiding jargon. So instead of "pharmacologically active," just say "the part that actually treats the condition."\n\nAlso, maybe mention that it\'s listed by its scientific or generic name. People might not recognize it, so that\'s why it\'s on the label. So even if two products are different brands, if the active ingredient is the same, they work the same way.\n\nLet me check if I have all points. Active ingredient is the key component that does the work, inactive are the others that help with delivery, necessity of labeling, examples. Yeah, that should cover it. I should avoid any complex explanations. Keep it conversational. Maybe start with an analogy? Like how in a recipe, the main ingredient that gives the dish its flavor is the active part, while others help in making it. Not sure if that\'s necessary, but simple analogies can help.\n\nAlso, make sure to clarify that the inactive ingredients don\'t contribute to the treatment, but they don\'t cause harm. They help with things like stability, absorption, etc. So together, active and inactive make up the whole drug. Maybe use a vitamin pill as an example, where the vitamin is the active ingredient and the rest are binders or coatings.\n\nOkay, putting it all together. Start by saying the active ingredient is the main part that treats the condition. Then contrast with inactive ones. Explain why it\'s important (labels, allergies, etc.). Use examples to make it clear. Keep sentences short and use easy words. Avoid saying "pharmacologically active" or terms that might not be familiar. Let me see if I missed anything. Maybe mention that it\'s different in each medication, so each has its own active ingredient(s) depending on what they\'re for. Like antibiotics vs. pain relievers have different actives targeting different issues.',
  'reasoning_details': [{'type': 'reasoning.text',
    'text': 'Okay, I need to explain what an active ingredient in medication means in simple terms. Let me start by recalling what I know. Medication usually has multiple components, right? The active ingredient is the part that actually does something to treat the condition. But I should make sure I\'m accurate.\n\nWait, so when you take a pill, the active ingredient is the part that\'s responsible for the effect. The rest are probably fillers or something to help the pill hold together. Like, maybe other substances help it dissolve properly or taste better. So the active ingredient is the actual drug that works on the body.\n\nI should mention that the active ingredient is the one that affects the body\'s process or targets a specific problem. For example, in pain relievers, maybe something like ibuprofen is the active ingredient. It reduces inflammation and pain. The other parts don\'t do much in terms of the effect, just help with delivery.\n\nOh, right, the FDA or other agencies require the active ingredient to be listed on the label. That\'s important for people with allergies or to avoid duplicates. So when reading a label, the active ingredient section tells you exactly what\'s in there that\'s making it work.\n\nAlso, different medications might have the same active ingredient but different brand names. Like acetaminophen can be found in Tylenol or other brands. That\'s why knowing the active ingredient is key when comparing medications.\n\nWait, are there examples I can use? Maybe aspirin, which has acetylsalicylic acid as the active ingredient. Or antihistamines for allergies, like loratadine. That\'s the part that makes it work, the rest are just to make it easier to take, maybe a coating or dyes.\n\nHmm, maybe I should structure it as: definition, role, contrast with inactive ingredients, why it\'s important to know, and examples. That way it covers all bases without getting too technical. Need to make sure the language is simple, avoiding jargon. So instead of "pharmacologically active," just say "the part that actually treats the condition."\n\nAlso, maybe mention that it\'s listed by its scientific or generic name. People might not recognize it, so that\'s why it\'s on the label. So even if two products are different brands, if the active ingredient is the same, they work the same way.\n\nLet me check if I have all points. Active ingredient is the key component that does the work, inactive are the others that help with delivery, necessity of labeling, examples. Yeah, that should cover it. I should avoid any complex explanations. Keep it conversational. Maybe start with an analogy? Like how in a recipe, the main ingredient that gives the dish its flavor is the active part, while others help in making it. Not sure if that\'s necessary, but simple analogies can help.\n\nAlso, make sure to clarify that the inactive ingredients don\'t contribute to the treatment, but they don\'t cause harm. They help with things like stability, absorption, etc. So together, active and inactive make up the whole drug. Maybe use a vitamin pill as an example, where the vitamin is the active ingredient and the rest are binders or coatings.\n\nOkay, putting it all together. Start by saying the active ingredient is the main part that treats the condition. Then contrast with inactive ones. Explain why it\'s important (labels, allergies, etc.). Use examples to make it clear. Keep sentences short and use easy words. Avoid saying "pharmacologically active" or terms that might not be familiar. Let me see if I missed anything. Maybe mention that it\'s different in each medication, so each has its own active ingredient(s) depending on what they\'re for. Like antibiotics vs. pain relievers have different actives targeting different issues.',
    'format': 'unknown',
    'index': 0}]}}

In [142]:
llm_data['choices'][0]['message']

{'role': 'assistant',
 'content': 'The **active ingredient** in a medication is the main part that **actually treats your health condition**. Think of it like the "star player" on a team—it’s the component that fights your symptoms or illness. For example, in a pain reliever like ibuprofen (found in Advil or Motrin), the active ingredient is ibuprofen itself, which reduces pain and inflammation.\n\n### What about the other stuff?\nMedications also contain **inactive ingredients**. These act like helpers—they might make the pill easier to swallow, help it dissolve properly, add color, or preserve it. They *don’t* treat your condition; they just help the active ingredient work better.\n\n### Why does it matter?\n- **Know what you’re taking**: The active ingredient is listed on medicine labels, so you can spot allergies, avoid duplicates (like taking two medicines with the same active ingredient), or choose a generic brand (which often has the same active ingredient as a more expensive brand name).\n- **Examples**:  \n  - In **Lipitor** (a cholesterol drug), the active ingredient is **atorvastatin**.  \n  - In **Zyrtec** (an allergy pill), it’s **loratadine**.  \n\n### Simple takeaway:\nThe active ingredient is the key "doer" in your medicine. Everything else is there to help it work, taste better, or look nice on the shelf. Always check the label to know what’s inside!',
 'refusal': None,
 'reasoning': 'Okay, I need to explain what an active ingredient in medication means in simple terms. Let me start by recalling what I know. Medication usually has multiple components, right? The active ingredient is the part that actually does something to treat the condition. But I should make sure I\'m accurate.\n\nWait, so when you take a pill, the active ingredient is the part that\'s responsible for the effect. The rest are probably fillers or something to help the pill hold together. Like, maybe other substances help it dissolve properly or taste better. So the active ingredient is the actual drug that works on the body.\n\nI should mention that the active ingredient is the one that affects the body\'s process or targets a specific problem. For example, in pain relievers, maybe something like ibuprofen is the active ingredient. It reduces inflammation and pain. The other parts don\'t do much in terms of the effect, just help with delivery.\n\nOh, right, the FDA or other agencies require the active ingredient to be listed on the label. That\'s important for people with allergies or to avoid duplicates. So when reading a label, the active ingredient section tells you exactly what\'s in there that\'s making it work.\n\nAlso, different medications might have the same active ingredient but different brand names. Like acetaminophen can be found in Tylenol or other brands. That\'s why knowing the active ingredient is key when comparing medications.\n\nWait, are there examples I can use? Maybe aspirin, which has acetylsalicylic acid as the active ingredient. Or antihistamines for allergies, like loratadine. That\'s the part that makes it work, the rest are just to make it easier to take, maybe a coating or dyes.\n\nHmm, maybe I should structure it as: definition, role, contrast with inactive ingredients, why it\'s important to know, and examples. That way it covers all bases without getting too technical. Need to make sure the language is simple, avoiding jargon. So instead of "pharmacologically active," just say "the part that actually treats the condition."\n\nAlso, maybe mention that it\'s listed by its scientific or generic name. People might not recognize it, so that\'s why it\'s on the label. So even if two products are different brands, if the active ingredient is the same, they work the same way.\n\nLet me check if I have all points. Active ingredient is the key component that does the work, inactive are the others that help with delivery, necessity of labeling, examples. Yeah, that should cover it. I should avoid any complex explanations. Keep it conversational. Maybe start with an analogy? Like how in a recipe, the main ingredient that gives the dish its flavor is the active part, while others help in making it. Not sure if that\'s necessary, but simple analogies can help.\n\nAlso, make sure to clarify that the inactive ingredients don\'t contribute to the treatment, but they don\'t cause harm. They help with things like stability, absorption, etc. So together, active and inactive make up the whole drug. Maybe use a vitamin pill as an example, where the vitamin is the active ingredient and the rest are binders or coatings.\n\nOkay, putting it all together. Start by saying the active ingredient is the main part that treats the condition. Then contrast with inactive ones. Explain why it\'s important (labels, allergies, etc.). Use examples to make it clear. Keep sentences short and use easy words. Avoid saying "pharmacologically active" or terms that might not be familiar. Let me see if I missed anything. Maybe mention that it\'s different in each medication, so each has its own active ingredient(s) depending on what they\'re for. Like antibiotics vs. pain relievers have different actives targeting different issues.',
 'reasoning_details': [{'type': 'reasoning.text',
   'text': 'Okay, I need to explain what an active ingredient in medication means in simple terms. Let me start by recalling what I know. Medication usually has multiple components, right? The active ingredient is the part that actually does something to treat the condition. But I should make sure I\'m accurate.\n\nWait, so when you take a pill, the active ingredient is the part that\'s responsible for the effect. The rest are probably fillers or something to help the pill hold together. Like, maybe other substances help it dissolve properly or taste better. So the active ingredient is the actual drug that works on the body.\n\nI should mention that the active ingredient is the one that affects the body\'s process or targets a specific problem. For example, in pain relievers, maybe something like ibuprofen is the active ingredient. It reduces inflammation and pain. The other parts don\'t do much in terms of the effect, just help with delivery.\n\nOh, right, the FDA or other agencies require the active ingredient to be listed on the label. That\'s important for people with allergies or to avoid duplicates. So when reading a label, the active ingredient section tells you exactly what\'s in there that\'s making it work.\n\nAlso, different medications might have the same active ingredient but different brand names. Like acetaminophen can be found in Tylenol or other brands. That\'s why knowing the active ingredient is key when comparing medications.\n\nWait, are there examples I can use? Maybe aspirin, which has acetylsalicylic acid as the active ingredient. Or antihistamines for allergies, like loratadine. That\'s the part that makes it work, the rest are just to make it easier to take, maybe a coating or dyes.\n\nHmm, maybe I should structure it as: definition, role, contrast with inactive ingredients, why it\'s important to know, and examples. That way it covers all bases without getting too technical. Need to make sure the language is simple, avoiding jargon. So instead of "pharmacologically active," just say "the part that actually treats the condition."\n\nAlso, maybe mention that it\'s listed by its scientific or generic name. People might not recognize it, so that\'s why it\'s on the label. So even if two products are different brands, if the active ingredient is the same, they work the same way.\n\nLet me check if I have all points. Active ingredient is the key component that does the work, inactive are the others that help with delivery, necessity of labeling, examples. Yeah, that should cover it. I should avoid any complex explanations. Keep it conversational. Maybe start with an analogy? Like how in a recipe, the main ingredient that gives the dish its flavor is the active part, while others help in making it. Not sure if that\'s necessary, but simple analogies can help.\n\nAlso, make sure to clarify that the inactive ingredients don\'t contribute to the treatment, but they don\'t cause harm. They help with things like stability, absorption, etc. So together, active and inactive make up the whole drug. Maybe use a vitamin pill as an example, where the vitamin is the active ingredient and the rest are binders or coatings.\n\nOkay, putting it all together. Start by saying the active ingredient is the main part that treats the condition. Then contrast with inactive ones. Explain why it\'s important (labels, allergies, etc.). Use examples to make it clear. Keep sentences short and use easy words. Avoid saying "pharmacologically active" or terms that might not be familiar. Let me see if I missed anything. Maybe mention that it\'s different in each medication, so each has its own active ingredient(s) depending on what they\'re for. Like antibiotics vs. pain relievers have different actives targeting different issues.',
   'format': 'unknown',
   'index': 0}]}

In [144]:
llm_data['choices'][0]['message']['content']

'The **active ingredient** in a medication is the main part that **actually treats your health condition**. Think of it like the "star player" on a team—it’s the component that fights your symptoms or illness. For example, in a pain reliever like ibuprofen (found in Advil or Motrin), the active ingredient is ibuprofen itself, which reduces pain and inflammation.\n\n### What about the other stuff?\nMedications also contain **inactive ingredients**. These act like helpers—they might make the pill easier to swallow, help it dissolve properly, add color, or preserve it. They *don’t* treat your condition; they just help the active ingredient work better.\n\n### Why does it matter?\n- **Know what you’re taking**: The active ingredient is listed on medicine labels, so you can spot allergies, avoid duplicates (like taking two medicines with the same active ingredient), or choose a generic brand (which often has the same active ingredient as a more expensive brand name).\n- **Examples**:  \n  - In **Lipitor** (a cholesterol drug), the active ingredient is **atorvastatin**.  \n  - In **Zyrtec** (an allergy pill), it’s **loratadine**.  \n\n### Simple takeaway:\nThe active ingredient is the key "doer" in your medicine. Everything else is there to help it work, taste better, or look nice on the shelf. Always check the label to know what’s inside!'

In [146]:
llm_answer = llm_data['choices'][0]['message']['content']

In [148]:
llm_answer

'The **active ingredient** in a medication is the main part that **actually treats your health condition**. Think of it like the "star player" on a team—it’s the component that fights your symptoms or illness. For example, in a pain reliever like ibuprofen (found in Advil or Motrin), the active ingredient is ibuprofen itself, which reduces pain and inflammation.\n\n### What about the other stuff?\nMedications also contain **inactive ingredients**. These act like helpers—they might make the pill easier to swallow, help it dissolve properly, add color, or preserve it. They *don’t* treat your condition; they just help the active ingredient work better.\n\n### Why does it matter?\n- **Know what you’re taking**: The active ingredient is listed on medicine labels, so you can spot allergies, avoid duplicates (like taking two medicines with the same active ingredient), or choose a generic brand (which often has the same active ingredient as a more expensive brand name).\n- **Examples**:  \n  - In **Lipitor** (a cholesterol drug), the active ingredient is **atorvastatin**.  \n  - In **Zyrtec** (an allergy pill), it’s **loratadine**.  \n\n### Simple takeaway:\nThe active ingredient is the key "doer" in your medicine. Everything else is there to help it work, taste better, or look nice on the shelf. Always check the label to know what’s inside!'

In [210]:
def get_llm_safety_summary(prompt):
    """
    Generate a simple medication safety summary using an LLM.

    Parameters:
        prompt (str): The medication-related question or information sent to the LLM.

    Returns:
        str: The final text response generated by the LLM.
    """
    llm_url = "https://openrouter.ai/api/v1/chat/completions"
    llm_headers ={"Authorization": f"Bearer {openrouter_key}","Content-Type": "application/json"}
    llm_payload = {"model":'openrouter/free','messages':[{
            "role": "system",
            "content": """
You are MediTrack's Medication Information Assistant.

Your role is to explain medication-related information in simple,
clear language.

Only answer questions related to:
- medications
- active ingredients
- medication uses
- side effects
- warnings
- drug interactions
- dosage instructions that are already provided by an authoritative source
- medication safety

Do not diagnose medical conditions.
Do not tell a user to start, stop, increase, or decrease a medication.
Do not replace the advice of a doctor or pharmacist.

When medication information from an external drug database is provided,
base your explanation primarily on that information.

If information is uncertain or unavailable, say so instead of guessing.

For potentially serious symptoms or emergencies, advise the user to
seek urgent professional medical help.

Keep explanations simple and concise.
"""
        },{'role':'user','content': prompt}]}
    llm_response = requests.post(llm_url,headers=llm_headers,json=llm_payload)
    if llm_response.status_code == 200:
        llm_data = llm_response.json()
        llm_answer = llm_data["choices"][0]["message"]["content"]
        return llm_answer
    else:
        print('LLM API Request failed. Status Code:',llm_response.status_code)
        print('LLM API response:',llm_response.text)
        return ""

In [212]:
test_summary = get_llm_safety_summary('explain the saftey warnings of aspirin in sample language ')

In [153]:
print(test_summary)

Here are aspirin safety warnings in simple language:

- **Allergy risk:** Don’t take aspirin if you’ve had hives, swelling, wheezing, or trouble breathing from aspirin or similar pain medicines.
- **Bleeding risk:** Aspirin can make you bleed more easily. Get help if you have black/tarry stools, vomit blood, cough up blood, or bleeding that won’t stop.
- **Stomach problems:** It can cause stomach irritation, ulcers, or stomach bleeding. Get help for severe stomach pain, vomiting blood, or feeling faint.
- **Children and teens:** Do **not** give aspirin to children or teens with a virus unless a doctor tells you to. It can cause **Reye’s syndrome**, a rare but serious illness.
- **Pregnancy:** Don’t use aspirin during pregnancy unless your doctor says it’s okay, especially in the last 3 months.
- **Blood thinners and other medicines:** Be careful if you take warfarin, clopidogrel, ibuprofen, naproxen, steroids, or many antidepressants. Ask a doctor or pharmacist first.
- **Alcohol:** Drinking alcohol increases the risk of stomach bleeding.
- **Surgery or dental work:** Tell your doctor/dentist you take aspirin. You may need to stop before procedures.
- **Asthma:** Aspirin can worsen breathing in some people with asthma.
- **Overdose:** Too much aspirin can be dangerous. Call Poison Control or emergency services if too much is taken.

**Get emergency help now** if you have trouble breathing, facial/throat swelling, chest pain, fainting, vomiting blood, black stools, or signs of a severe allergic reaction.

In [214]:
test_summary = get_llm_safety_summary('what is the side effects of effexor xr')

In [215]:
test_summary

'**Effexor XR (venlafaxine\u202fXR) – common side effects**\n\n- Nausea or upset stomach  \n- Dry mouth  \n- Trouble sleeping (insomnia) or feeling drowsy  \n- Dizziness or light‑headedness  \n- Sweating  \n- Constipation  \n- Sexual problems (e.g., reduced desire, difficulty reaching orgasm)  \n- Increased blood pressure  \n\n**Less common but more serious side effects**\n\n- Signs of serotonin syndrome: agitation, confusion, rapid heartbeat, high fever, muscle rigidity, sweating, tremor, or diarrhea.  \n- New or worsening thoughts of suicide, especially in people under 25 years old.  \n- Seizures.  \n- Severe high blood pressure or heart‑rate changes.  \n\nIf you notice any of the serious symptoms above, seek urgent medical help right away.  \n\n*This information is a general overview and not a substitute for professional medical advice. Always talk with your doctor or pharmacist if you have concerns about side effects.*'

In [218]:
test_summary = get_llm_safety_summary('tell me about ferrari cars ')

# CSV Data Design

MediTrack will use CSV files to store medication records, intake history, and wellness information.

The main medication file will be `medications.csv`.
Each row will represent one medication added by the user.

In [161]:
medication_columns =['medication_id','medication_name','ingredients_substances','symptoms_tags','dosage_frequency_value','dosage_frequency_unit','usage_safety_instructions','urgency_level','medication_type','dose_quantity','dose_unit','start_time','current_supply','refill_threshold','expiration_date','compliance_rating','api_generic_name','api_substances']

In [163]:
import pandas as pd

In [165]:
medications_df = pd.DataFrame(columns=medication_columns)

In [167]:
medications_df

Empty DataFrame
Columns: [medication_id, medication_name, ingredients_substances, symptoms_tags, dosage_frequency_value, dosage_frequency_unit, usage_safety_instructions, urgency_level, medication_type, dose_quantity, dose_unit, start_time, current_supply, refill_threshold, expiration_date, compliance_rating, api_generic_name, api_substances]
Index: []

In [169]:
medications_df.to_csv('medications.csv',index=False)

In [171]:
def load_medications():
    """
    Load saved medication records from medications.csv.

    Returns:
        DataFrame: The saved medication records.
    """
    if os.path.exists('medications.csv'):
        return pd.read_csv('medications.csv')
    else:
        return pd.DataFrame(columns = medication_columns)

In [173]:
loaded_medications = load_medications()

In [175]:
loaded_medications

Empty DataFrame
Columns: [medication_id, medication_name, ingredients_substances, symptoms_tags, dosage_frequency_value, dosage_frequency_unit, usage_safety_instructions, urgency_level, medication_type, dose_quantity, dose_unit, start_time, current_supply, refill_threshold, expiration_date, compliance_rating, api_generic_name, api_substances]
Index: []

In [177]:
def save_medications(medications_df):
    """
    Save medication records to medications.csv.

    Parameters:
        medications_df (DataFrame): The medication records to save.
    """
    medications_df.to_csv("medications.csv", index=False)

In [344]:
def add_medication (medications_df,medication_name,ingredients_substances,dosage_frequency_value,dosage_frequency_unit,usage_safety_instructions,urgency_level,symptoms_tags="",
    start_time="",
    current_supply="",
    refill_threshold="",
    expiration_date=""):
    """
    Add a new medication record to the tracker.

    Parameters:
        medications_df (DataFrame): Current medication records.
        medication_name (str): Name of the medication.
        ingredients_substances (str): Ingredients or interacting substances.
        dosage_frequency_value (int): Frequency number.
        dosage_frequency_unit (str): Hours or Minutes.
        usage_safety_instructions (str): Usage and safety instructions.
        urgency_level (str): Low, Medium, or High.

    Returns:
        DataFrame: Updated medication records.
    """
    if is_duplicate_medication(medications_df, medication_name):
        return medications_df
    
    if medications_df.empty:
        medication_id = 1
    else:
        medication_id = medications_df['medication_id'].max()+1
        
    new_medication = {"medication_id": medication_id,
    "medication_name": medication_name,
    "ingredients_substances": ingredients_substances,
    "symptoms_tags": symptoms_tags,
    "dosage_frequency_value": dosage_frequency_value,
    "dosage_frequency_unit": dosage_frequency_unit,
    "usage_safety_instructions": usage_safety_instructions,
    "urgency_level": urgency_level,
    "medication_type": "",
    "dose_quantity": "",
    "dose_unit": "",
    "start_time": start_time,
    "current_supply": current_supply,
    "refill_threshold": refill_threshold,
    "expiration_date": expiration_date,
    "compliance_rating": "",
    "api_generic_name": "",
    "api_substances": ""}

    medications_df.loc[len(medications_df)]= new_medication
    save_medications(medications_df)
    
    return medications_df

In [350]:
#test after update
medications_df = add_medication(
    medications_df,
    "Panadol",
    "Paracetamol",
    8,
    "Hours",
    "Take with water",
    "Medium",
    "headache, fever, pain",
    "08:00",
    20,
    5,
    "2027-01-01"
)

medications_df

,medication_id,medication_name,ingredients_substances,symptoms_tags,dosage_frequency_value,dosage_frequency_unit,usage_safety_instructions,urgency_level,medication_type,dose_quantity,dose_unit,start_time,current_supply,refill_threshold,expiration_date,compliance_rating,api_generic_name,api_substances
0,1,Ibuprofen,Ibuprofen,NaN,8,Hours,Take with food,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Aspirin,Aspirin,,6,Hours,Take with water,Low,,,,,,,,,,
2,3,Panadol,Paracetamol,"headache, fever, pain",8,Hours,Take with water,Medium,,,,08:00,20,5,2027-01-01,,,

In [352]:
medications_df[
    [
        "medication_name",
        "symptoms_tags",
        "start_time",
        "current_supply",
        "refill_threshold",
        "expiration_date"
    ]
]

,medication_name,symptoms_tags,start_time,current_supply,refill_threshold,expiration_date
0,Ibuprofen,NaN,NaN,NaN,NaN,NaN
1,Aspirin,,,,,
2,Panadol,"headache, fever, pain",08:00,20,5,2027-01-01

In [181]:
##testing the function
medications_df = add_medication(medications_df,"Ibuprofen","Ibuprofen",8,"Hours","Take with food","Medium")

In [198]:
medications_df

,medication_id,medication_name,ingredients_substances,symptoms_tags,dosage_frequency_value,dosage_frequency_unit,usage_safety_instructions,urgency_level,medication_type,dose_quantity,dose_unit,start_time,current_supply,refill_threshold,expiration_date,compliance_rating,api_generic_name,api_substances
0,1,Ibuprofen,Ibuprofen,NaN,8,Hours,Take with food,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
pd.read_csv('medications.csv')

,medication_id,medication_name,ingredients_substances,symptoms_tags,dosage_frequency_value,dosage_frequency_unit,usage_safety_instructions,urgency_level,medication_type,dose_quantity,dose_unit,start_time,current_supply,refill_threshold,expiration_date,compliance_rating,api_generic_name,api_substances
0,1,Ibuprofen,Ibuprofen,NaN,8,Hours,Take with food,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [188]:
medications_df = load_medications()

print("Number of columns:", len(medications_df.columns))
print(medications_df.columns.tolist())

Number of columns: 18
['medication_id', 'medication_name', 'ingredients_substances', 'symptoms_tags', 'dosage_frequency_value', 'dosage_frequency_unit', 'usage_safety_instructions', 'urgency_level', 'medication_type', 'dose_quantity', 'dose_unit', 'start_time', 'current_supply', 'refill_threshold', 'expiration_date', 'compliance_rating', 'api_generic_name', 'api_substances']

In [220]:
def search_saved_medications(medications_df,search_text):
    """
    Search saved medications by medication name,
    ingredient/substance, or symptom tag.

    Parameters:
        medications_df (DataFrame): Saved medication records.
        search_text (str): Text entered by the user.

    Returns:
        DataFrame: Matching medication records.
    """
    search_text=search_text.strip().lower()
    if search_text =="":
        return pd.DataFrame(columns=medications_df.columns)
    name_match = (medications_df["medication_name"].fillna("").astype(str).str.lower().str.contains(search_text, regex=False))
    ingredient_match = (medications_df["ingredients_substances"].fillna("").astype(str).str.lower().str.contains(search_text, regex=False))
    symptom_match = (medications_df["symptoms_tags"].fillna("").astype(str).str.lower().str.contains(search_text, regex=False))
    matches = medications_df[name_match | ingredient_match | symptom_match]
    return matches

In [208]:
search_saved_medications(medications_df, "     ")

Empty DataFrame
Columns: [medication_id, medication_name, ingredients_substances, symptoms_tags, dosage_frequency_value, dosage_frequency_unit, usage_safety_instructions, urgency_level, medication_type, dose_quantity, dose_unit, start_time, current_supply, refill_threshold, expiration_date, compliance_rating, api_generic_name, api_substances]
Index: []

In [222]:
search_saved_medications(medications_df, "ibuprofen")

,medication_id,medication_name,ingredients_substances,symptoms_tags,dosage_frequency_value,dosage_frequency_unit,usage_safety_instructions,urgency_level,medication_type,dose_quantity,dose_unit,start_time,current_supply,refill_threshold,expiration_date,compliance_rating,api_generic_name,api_substances
0,1,Ibuprofen,Ibuprofen,NaN,8,Hours,Take with food,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [224]:
search_saved_medications(medications_df, "ibu")

,medication_id,medication_name,ingredients_substances,symptoms_tags,dosage_frequency_value,dosage_frequency_unit,usage_safety_instructions,urgency_level,medication_type,dose_quantity,dose_unit,start_time,current_supply,refill_threshold,expiration_date,compliance_rating,api_generic_name,api_substances
0,1,Ibuprofen,Ibuprofen,NaN,8,Hours,Take with food,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [226]:
search_saved_medications(medications_df, "aspirin")

Empty DataFrame
Columns: [medication_id, medication_name, ingredients_substances, symptoms_tags, dosage_frequency_value, dosage_frequency_unit, usage_safety_instructions, urgency_level, medication_type, dose_quantity, dose_unit, start_time, current_supply, refill_threshold, expiration_date, compliance_rating, api_generic_name, api_substances]
Index: []

In [230]:
def is_duplicate_medication(medications_df, medication_name):
    """
    Check whether a medication is already saved.

    Parameters:
        medications_df (DataFrame): Saved medication records.
        medication_name (str): Medication name to check.

    Returns:
        bool: True if medication already exists, otherwise False.
    """
    medication_name = medication_name.strip().lower()
    if medications_df.empty:
        return False
    saved_names = (medications_df["medication_name"].fillna("").astype(str).str.strip().str.lower())
    return medication_name in saved_names.values

In [232]:
is_duplicate_medication(medications_df, "  IBUPROFEN  ")

True

In [234]:
is_duplicate_medication(medications_df, "  IBUPROFEN  ")

True

In [236]:
is_duplicate_medication(medications_df, "Aspirin")

False

In [242]:
len(medications_df)

1

In [244]:
medications_df = add_medication(
    medications_df,
    "Ibuprofen",
    "Ibuprofen",
    8,
    "Hours",
    "Take with food",
    "Medium"
)

In [246]:
len(medications_df)

1

In [248]:
medications_df = add_medication(
    medications_df,
    "Aspirin",
    "Aspirin",
    6,
    "Hours",
    "Take with water",
    "Low"
)

In [250]:
len(medications_df)

2

In [252]:
medications_df

,medication_id,medication_name,ingredients_substances,symptoms_tags,dosage_frequency_value,dosage_frequency_unit,usage_safety_instructions,urgency_level,medication_type,dose_quantity,dose_unit,start_time,current_supply,refill_threshold,expiration_date,compliance_rating,api_generic_name,api_substances
0,1,Ibuprofen,Ibuprofen,NaN,8,Hours,Take with food,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Aspirin,Aspirin,,6,Hours,Take with water,Low,,,,,,,,,,

In [254]:
def process_api_results(api_results):
    """
    Convert raw RapidAPI medication results into
    cleaner records for MediTrack.

    Parameters:
        api_results (list): Raw medication records returned by RapidAPI.

    Returns:
        list: Cleaned medication records.
    """
    cleaned_results = []
    for medication in api_results:
        substances = medication.get("substance_name", [])
        if isinstance(substances, list):
            substances = ", ".join(substances)

        cleaned_medication = {"brand_name": medication.get("brand_name", "Unknown"),"generic_name": medication.get("generic_name", "Unknown"),
            "substances": substances,"route": medication.get("route", []),"dosage_form": medication.get("dosage_form", "Unknown"),
            "purpose": medication.get("purpose", "Not available"),"warnings": medication.get("warnings", "Not available"),"indications_and_usage": medication.get("indications_and_usage","Not available")}

        cleaned_results.append(cleaned_medication)

    return cleaned_results

In [256]:
## testing the function

In [258]:
api_results = search_medication_api("aspirin")

cleaned_results = process_api_results(api_results)

cleaned_results[0]

{'brand_name': 'Low Dose Aspirin',
 'generic_name': 'ASPIRIN',
 'substances': 'ASPIRIN',
 'route': ['ORAL'],
 'dosage_form': None,
 'purpose': 'Purpose Pain reliever',
 'warnings': "Warnings Reye's syndrome : Children and teenagers who have or are recovering from chicken pox or flu-like symptoms should not use this product. When using this product, if changes in behavior with nausea and vomiting occur, consult a doctor because these symptoms could be an early sign of Reye's syndrome, a rare but serious illness. Allergy alert : Aspirin may cause a severe allergic reaction, which may include: hives facial swelling shock asthma (wheezing) Stomach bleeding warning: This product contains an NSAID, which may cause severe stomach bleeding. The chance is higher if you: are age 60 or older have had stomach ulcers or bleeding problems take a blood thinning (anticoagulant) or steroid drug take other drugs containing prescription or nonprescription NSAIDs [aspirin, ibuprofen, naproxen, or others] have 3 or more alcoholic drinks every day while using this product take more or for a longer time than directed Do not use if you are allergic to aspirin or any other pain reliever/f",
 'indications_and_usage': 'Uses for the temporary relief of minor aches and pains or as recommended by your doctor. Because of its delayed action, this product will not provide fast relief of headaches or other symptoms needing immediate relief. ask your doctor about other uses for safety coated 81 mg aspirin'}

In [260]:
len(cleaned_results)

10

In [262]:
type(cleaned_results)

list

In [264]:
type(cleaned_results[0])

dict

In [266]:
def check_shared_ingredient_risk(medications_df, search_text):
    """
    Check whether the searched ingredient appears
    in more than one saved medication.

    Returns:
        list: Names of medications containing the ingredient.
    """

    search_text = search_text.strip().lower()
    if search_text == "":
        return []
    ingredient_match = (medications_df["ingredients_substances"].fillna("").astype(str).str.lower().str.contains(search_text, regex=False))
    matching_medications = medications_df.loc[ingredient_match,"medication_name"].tolist()

    return matching_medications

In [268]:
check_shared_ingredient_risk(medications_df, "ibuprofen")

['Ibuprofen']

In [270]:
test_df = pd.concat([medications_df,pd.DataFrame([{"medication_name": "Advil","ingredients_substances": "Ibuprofen"}])],ignore_index=True)

In [272]:
risk_meds = check_shared_ingredient_risk(test_df,"ibuprofen")

risk_meds

['Ibuprofen', 'Advil']

In [274]:
if len(risk_meds) > 1:
    print("Warning: This ingredient appears in multiple medications.")
else:
    print("No shared ingredient risk found.")

Warning: This ingredient appears in multiple medications.

In [276]:
from datetime import datetime, timedelta

In [278]:
def calculate_next_intake(start_time, frequency_value, frequency_unit):
    """
    Calculate the next scheduled intake time.

    Parameters:
        start_time (str): First dose time in HH:MM format.
        frequency_value (int): Frequency number.
        frequency_unit (str): Hours or Minutes.

    Returns:
        datetime: Next scheduled intake time.
    """
    if pd.isna(start_time) or str(start_time).strip() == "":
        return None

    try:
        start = datetime.strptime(str(start_time),"%H:%M").replace(year=datetime.now().year,month=datetime.now().month,day=datetime.now().day)
        frequency_value = int(frequency_value)

        if str(frequency_unit).lower().startswith("hour"):
            interval = timedelta(hours=frequency_value)
        else:
            interval = timedelta(minutes=frequency_value)

        next_time = start

        while next_time <= datetime.now():
            next_time += interval

        return next_time

    except (ValueError, TypeError):
        return None

In [280]:
next_dose = calculate_next_intake("08:00",8,"Hours")

next_dose

datetime.datetime(2026, 9, 22, 16, 0)

In [282]:
next_dose.strftime("%I:%M %p")

'04:00 PM'

In [284]:
def generate_daily_schedule(medications_df):
    """
    Generate a chronological medication schedule
    for a 24-hour day.

    Parameters:
        medications_df (DataFrame): Saved medication records.

    Returns:
        list: Scheduled medication doses with their times.
    """

    schedule = []

    today = datetime.now().date()

    for _, medication in medications_df.iterrows():

        start_time = medication["start_time"]

        if pd.isna(start_time) or str(start_time).strip() == "":
            continue

        try:
            first_dose = datetime.strptime(str(start_time),"%H:%M")
            current_dose = datetime.combine(today,first_dose.time())

            frequency_value = int(medication["dosage_frequency_value"])

            if frequency_value <= 0:
                continue

            frequency_unit = str(medication["dosage_frequency_unit"]).lower()

            if frequency_unit.startswith("hour"):
                interval = timedelta(hours=frequency_value)
            else:
                interval = timedelta(minutes=frequency_value)

            end_of_day = datetime.combine(today + timedelta(days=1),datetime.min.time())

            while current_dose < end_of_day:

                schedule.append({"medication_name": medication["medication_name"],"time": current_dose})

                current_dose += interval

        except (ValueError, TypeError):
            continue

    schedule.sort(key=lambda item: item["time"])

    return schedule

In [288]:
test_schedule_df = medications_df.copy()
test_schedule_df.loc[test_schedule_df["medication_name"] == "Ibuprofen","start_time"] = "08:00"

In [290]:
daily_schedule = generate_daily_schedule(test_schedule_df)

daily_schedule

[{'medication_name': 'Ibuprofen',
  'time': datetime.datetime(2026, 9, 22, 8, 0)},
 {'medication_name': 'Ibuprofen',
  'time': datetime.datetime(2026, 9, 22, 16, 0)}]

In [292]:
for dose in daily_schedule:
    print(dose["time"].strftime("%I:%M %p"),"-",dose["medication_name"])

08:00 AM - Ibuprofen
04:00 PM - Ibuprofen

In [296]:
def check_expiration_status(expiration_date, warning_days=7):
    """
    Check whether a medication is expired,
    expiring soon, or still okay.

    Parameters:
        expiration_date (str): Medication expiration date.
        warning_days (int): Number of days before expiry to warn the user.

    Returns:
        str: Expired, Expiring Soon, OK, or Unknown.
    """

    if pd.isna(expiration_date) or str(expiration_date).strip() == "":
        return "Unknown"

    try:
        expiration = pd.to_datetime(expiration_date).date()
        today = datetime.now().date()

        days_remaining = (expiration - today).days

        if days_remaining < 0:
            return "Expired"

        elif days_remaining <= warning_days:
            return "Expiring Soon"

        else:
            return "OK"

    except (ValueError, TypeError):
        return "Unknown"

In [298]:
check_expiration_status("2026-09-20")

'Expired'

In [300]:
check_expiration_status("2026-09-27")

'Expiring Soon'

In [302]:
check_expiration_status("2026-10-15")

'OK'

In [304]:
check_expiration_status("")

'Unknown'

In [306]:
def check_low_supply(current_supply, refill_threshold):
    """
    Check whether the current medication supply
    has reached or gone below the refill threshold.

    Parameters:
        current_supply (float/int): Amount of medication currently available.
        refill_threshold (float/int): Minimum amount before refill warning.

    Returns:
        bool: True if supply is low, otherwise False.
    """

    try:
        return float(current_supply) <= float(refill_threshold)

    except (ValueError, TypeError):
        return False

In [308]:
check_low_supply(5, 10)

True

In [310]:
check_low_supply(15, 10)

False

In [312]:
check_low_supply(10, 10)

True

In [314]:
check_low_supply("five", 10)

False

In [326]:
import random

In [328]:
def get_random_wellness_spotlight():
    """
    Generate a random wellness tip or medication spotlight
    using the OpenRouter API.

    Returns:
        dict: Type and generated content.
    """

    spotlight_type = random.choice(["Wellness Tip", "Medication Spotlight"])

    prompt = f"""
Generate one short {spotlight_type} for a medication tracking application.

Rules:
- Keep it simple and useful.
- Maximum 2 sentences.
- Do not diagnose medical conditions.
- Do not recommend changing medication doses.
- Do not tell users to start or stop prescription medication.
- Do not provide personalized medical advice.
- Return only the {spotlight_type}, with no heading.
"""

    payload = {
        "model": "openrouter/free", "temperature": 1.0 ,
        "messages": [
            {
                "role": "system",
                "content": """
You are MediTrack's wellness and medication information assistant.
Provide safe, clear, general health and medication education.
Do not diagnose, prescribe, or change a user's treatment.
"""
            },{"role": "user","content": prompt}]}

    try:
        response = requests.post(llm_url,headers=llm_headers,json=payload)

        if response.status_code == 200:
            data = response.json()

            content = (data["choices"][0]["message"]["content"].strip())

            return {"type": spotlight_type,"content": content}

        return {"type": "Wellness Tip","content": "Stay hydrated and follow your medication instructions carefully."}

    except (requests.RequestException, KeyError, IndexError, TypeError):
        return {"type": "Wellness Tip","content": "Stay hydrated and follow your medication instructions carefully."}

In [330]:
spotlight = get_random_wellness_spotlight()

spotlight

{'type': 'Wellness Tip',
 'content': 'Set a consistent daily reminder to help you stay on track with your medications and wellness routine.'}

In [332]:
def delete_medications(medications_df, medication_ids=None, delete_all=False):
    """
    Delete one, multiple, or all medications.

    Parameters:
        medications_df (DataFrame): Saved medication records.
        medication_ids (list): IDs of medications to delete.
        delete_all (bool): If True, delete all medications.

    Returns:
        DataFrame: Updated medication records.
    """

    if delete_all:
        return medications_df.iloc[0:0].copy()

    if medication_ids:
        updated_df = medications_df[~medications_df["medication_id"].isin(medication_ids)].copy()

        return updated_df

    return medications_df.copy()

In [334]:
test_delete_df = pd.DataFrame([
    {"medication_id": 1, "medication_name": "Ibuprofen"},
    {"medication_id": 2, "medication_name": "Aspirin"},
    {"medication_id": 3, "medication_name": "Vitamin D3"}
])

In [336]:
delete_medications(test_delete_df, [2])

   medication_id medication_name
0              1       Ibuprofen
2              3      Vitamin D3

In [338]:
delete_medications(test_delete_df, [1, 3])

   medication_id medication_name
1              2         Aspirin

In [340]:
delete_medications(test_delete_df, delete_all=True)

Empty DataFrame
Columns: [medication_id, medication_name]
Index: []

In [374]:
## creating myutils.py file

In [356]:
%%writefile myutils.py
%%writefile myutils.py

import os
import random
from datetime import datetime, timedelta

import pandas as pd
import requests
from dotenv import load_dotenv


# =========================================================
# ENVIRONMENT / API CONFIGURATION
# =========================================================

load_dotenv()

rapidapi_key = os.getenv("RAPIDAPI_KEY")
openrouter_key = os.getenv("OPENROUTER_API_KEY")

llm_url = "https://openrouter.ai/api/v1/chat/completions"

llm_headers = {
    "Authorization": f"Bearer {openrouter_key}",
    "Content-Type": "application/json"
}


# =========================================================
# MEDICATION DATA STRUCTURE
# =========================================================

medication_columns = [
    "medication_id",
    "medication_name",
    "ingredients_substances",
    "symptoms_tags",
    "dosage_frequency_value",
    "dosage_frequency_unit",
    "usage_safety_instructions",
    "urgency_level",
    "medication_type",
    "dose_quantity",
    "dose_unit",
    "start_time",
    "current_supply",
    "refill_threshold",
    "expiration_date",
    "compliance_rating",
    "api_generic_name",
    "api_substances"
]


# =========================================================
# EXTERNAL MEDICATION API
# =========================================================

def search_medication_api(medication_name):
    """
    Search the external medication API using a medication name.

    Parameters:
        medication_name (str): Medication name entered by the user.

    Returns:
        list: Medication records returned by the API.
    """

    url = (
        "https://drug-information-api-fda-labels-and-ndc-lookup."
        "p.rapidapi.com/drugs/search"
    )

    querystring = {
        "limit": "10",
        "q": medication_name
    }

    headers = {
        "x-rapidapi-key": rapidapi_key,
        "x-rapidapi-host":
            "drug-information-api-fda-labels-and-ndc-lookup.p.rapidapi.com",
        "Content-Type": "application/json"
    }

    response = requests.get(
        url,
        headers=headers,
        params=querystring
    )

    if response.status_code == 200:
        return response.json()

    return []


def process_api_results(api_results):
    """
    Convert raw RapidAPI medication results into cleaner records.

    Parameters:
        api_results (list): Raw medication records from RapidAPI.

    Returns:
        list: Cleaned medication records.
    """

    cleaned_results = []

    for medication in api_results:

        substances = medication.get("substance_name", [])

        if isinstance(substances, list):
            substances = ", ".join(substances)

        cleaned_medication = {
            "brand_name": medication.get("brand_name", "Unknown"),
            "generic_name": medication.get("generic_name", "Unknown"),
            "substances": substances,
            "route": medication.get("route", []),
            "dosage_form": medication.get("dosage_form", "Unknown"),
            "purpose": medication.get("purpose", "Not available"),
            "warnings": medication.get("warnings", "Not available"),
            "indications_and_usage": medication.get(
                "indications_and_usage",
                "Not available"
            )
        }

        cleaned_results.append(cleaned_medication)

    return cleaned_results


# =========================================================
# WELLNESS / MEDICATION SPOTLIGHT
# =========================================================

def get_random_wellness_spotlight():
    """
    Generate a random wellness tip or medication spotlight
    using the OpenRouter API.

    Returns:
        dict: Type and generated content.
    """

    spotlight_type = random.choice(
        ["Wellness Tip", "Medication Spotlight"]
    )

    prompt = f"""
Generate one short {spotlight_type} for a medication tracking application.

Rules:
- Keep it simple and useful.
- Maximum 2 sentences.
- Do not diagnose medical conditions.
- Do not recommend changing medication doses.
- Do not tell users to start or stop prescription medication.
- Do not provide personalized medical advice.
- Return only the {spotlight_type}, with no heading.
"""

    payload = {
        "model": "openrouter/free",
        "temperature": 1.0,
        "messages": [
            {
                "role": "system",
                "content": """
You are MediTrack's wellness and medication information assistant.
Provide safe, clear, general health and medication education.
Do not diagnose, prescribe, or change a user's treatment.
"""
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    }

    try:
        response = requests.post(
            llm_url,
            headers=llm_headers,
            json=payload
        )

        if response.status_code == 200:
            data = response.json()

            content = (
                data["choices"][0]["message"]["content"]
                .strip()
            )

            return {
                "type": spotlight_type,
                "content": content
            }

        return {
            "type": "Wellness Tip",
            "content":
                "Stay hydrated and follow your medication instructions carefully."
        }

    except (
        requests.RequestException,
        KeyError,
        IndexError,
        TypeError
    ):
        return {
            "type": "Wellness Tip",
            "content":
                "Stay hydrated and follow your medication instructions carefully."
        }


# =========================================================
# CSV LOAD / SAVE
# =========================================================

def load_medications():
    """
    Load saved medication records from medications.csv.

    Returns:
        DataFrame: Saved medication records.
    """

    if os.path.exists("medications.csv"):
        return pd.read_csv("medications.csv")

    return pd.DataFrame(columns=medication_columns)


def save_medications(medications_df):
    """
    Save medication records to medications.csv.

    Parameters:
        medications_df (DataFrame): Medication records to save.
    """

    medications_df.to_csv(
        "medications.csv",
        index=False
    )


# =========================================================
# DUPLICATE CHECK
# =========================================================

def is_duplicate_medication(medications_df, medication_name):
    """
    Check whether a medication is already saved.

    Returns:
        bool: True if medication exists, otherwise False.
    """

    medication_name = medication_name.strip().lower()

    if medications_df.empty:
        return False

    saved_names = (
        medications_df["medication_name"]
        .fillna("")
        .astype(str)
        .str.strip()
        .str.lower()
    )

    return medication_name in saved_names.values


# =========================================================
# ADD MEDICATION
# =========================================================

def add_medication(
    medications_df,
    medication_name,
    ingredients_substances,
    dosage_frequency_value,
    dosage_frequency_unit,
    usage_safety_instructions,
    urgency_level,
    symptoms_tags="",
    start_time="",
    current_supply="",
    refill_threshold="",
    expiration_date=""
):
    """
    Add a new medication record to the tracker.

    Returns:
        DataFrame: Updated medication records.
    """

    if is_duplicate_medication(
        medications_df,
        medication_name
    ):
        return medications_df

    if medications_df.empty:
        medication_id = 1
    else:
        medication_id = (
            medications_df["medication_id"].max() + 1
        )

    new_medication = {
        "medication_id": medication_id,
        "medication_name": medication_name,
        "ingredients_substances": ingredients_substances,
        "symptoms_tags": symptoms_tags,
        "dosage_frequency_value": dosage_frequency_value,
        "dosage_frequency_unit": dosage_frequency_unit,
        "usage_safety_instructions": usage_safety_instructions,
        "urgency_level": urgency_level,
        "medication_type": "",
        "dose_quantity": "",
        "dose_unit": "",
        "start_time": start_time,
        "current_supply": current_supply,
        "refill_threshold": refill_threshold,
        "expiration_date": expiration_date,
        "compliance_rating": "",
        "api_generic_name": "",
        "api_substances": ""
    }

    medications_df.loc[len(medications_df)] = new_medication

    save_medications(medications_df)

    return medications_df


# =========================================================
# SEARCH SAVED MEDICATIONS
# =========================================================

def search_saved_medications(
    medications_df,
    search_text
):
    """
    Search saved medications by medication name,
    ingredient/substance, or symptom tag.

    Returns:
        DataFrame: Matching medication records.
    """

    search_text = search_text.strip().lower()

    if search_text == "":
        return pd.DataFrame(
            columns=medications_df.columns
        )

    name_match = (
        medications_df["medication_name"]
        .fillna("")
        .astype(str)
        .str.lower()
        .str.contains(search_text, regex=False)
    )

    ingredient_match = (
        medications_df["ingredients_substances"]
        .fillna("")
        .astype(str)
        .str.lower()
        .str.contains(search_text, regex=False)
    )

    symptom_match = (
        medications_df["symptoms_tags"]
        .fillna("")
        .astype(str)
        .str.lower()
        .str.contains(search_text, regex=False)
    )

    matches = medications_df[
        name_match |
        ingredient_match |
        symptom_match
    ]

    return matches


# =========================================================
# SHARED INGREDIENT RISK
# =========================================================

def check_shared_ingredient_risk(
    medications_df,
    search_text
):
    """
    Find saved medications containing the same
    searched ingredient.

    Returns:
        list: Matching medication names.
    """

    search_text = search_text.strip().lower()

    if search_text == "":
        return []

    ingredient_match = (
        medications_df["ingredients_substances"]
        .fillna("")
        .astype(str)
        .str.lower()
        .str.contains(search_text, regex=False)
    )

    matching_medications = medications_df.loc[
        ingredient_match,
        "medication_name"
    ].tolist()

    return matching_medications


# =========================================================
# NEXT INTAKE
# =========================================================

def calculate_next_intake(
    start_time,
    frequency_value,
    frequency_unit
):
    """
    Calculate the next scheduled medication intake time.

    Returns:
        datetime or None.
    """

    if (
        pd.isna(start_time)
        or str(start_time).strip() == ""
    ):
        return None

    try:
        start = datetime.strptime(
            str(start_time),
            "%H:%M"
        ).replace(
            year=datetime.now().year,
            month=datetime.now().month,
            day=datetime.now().day
        )

        frequency_value = int(frequency_value)

        if (
            str(frequency_unit)
            .lower()
            .startswith("hour")
        ):
            interval = timedelta(
                hours=frequency_value
            )
        else:
            interval = timedelta(
                minutes=frequency_value
            )

        next_time = start

        while next_time <= datetime.now():
            next_time += interval

        return next_time

    except (ValueError, TypeError):
        return None


# =========================================================
# DAILY 24-HOUR SCHEDULE
# =========================================================

def generate_daily_schedule(medications_df):
    """
    Generate a chronological medication schedule
    for a 24-hour day.

    Returns:
        list: Medication names and scheduled times.
    """

    schedule = []

    today = datetime.now().date()

    for _, medication in medications_df.iterrows():

        start_time = medication["start_time"]

        if (
            pd.isna(start_time)
            or str(start_time).strip() == ""
        ):
            continue

        try:
            first_dose = datetime.strptime(
                str(start_time),
                "%H:%M"
            )

            current_dose = datetime.combine(
                today,
                first_dose.time()
            )

            frequency_value = int(
                medication[
                    "dosage_frequency_value"
                ]
            )

            if frequency_value <= 0:
                continue

            frequency_unit = str(
                medication[
                    "dosage_frequency_unit"
                ]
            ).lower()

            if frequency_unit.startswith("hour"):
                interval = timedelta(
                    hours=frequency_value
                )
            else:
                interval = timedelta(
                    minutes=frequency_value
                )

            end_of_day = datetime.combine(
                today + timedelta(days=1),
                datetime.min.time()
            )

            while current_dose < end_of_day:

                schedule.append({
                    "medication_name":
                        medication["medication_name"],
                    "time": current_dose
                })

                current_dose += interval

        except (ValueError, TypeError):
            continue

    schedule.sort(
        key=lambda item: item["time"]
    )

    return schedule


# =========================================================
# EXPIRATION CHECK
# =========================================================

def check_expiration_status(
    expiration_date,
    warning_days=7
):
    """
    Check whether medication is expired,
    expiring soon, or okay.

    Returns:
        str: Expired, Expiring Soon, OK, or Unknown.
    """

    if (
        pd.isna(expiration_date)
        or str(expiration_date).strip() == ""
    ):
        return "Unknown"

    try:
        expiration = (
            pd.to_datetime(expiration_date)
            .date()
        )

        today = datetime.now().date()

        days_remaining = (
            expiration - today
        ).days

        if days_remaining < 0:
            return "Expired"

        elif days_remaining <= warning_days:
            return "Expiring Soon"

        else:
            return "OK"

    except (ValueError, TypeError):
        return "Unknown"


# =========================================================
# LOW SUPPLY CHECK
# =========================================================

def check_low_supply(
    current_supply,
    refill_threshold
):
    """
    Check whether medication supply is low.

    Returns:
        bool: True when refill warning is needed.
    """

    try:
        return (
            float(current_supply)
            <= float(refill_threshold)
        )

    except (ValueError, TypeError):
        return False


# =========================================================
# DELETE MEDICATIONS
# =========================================================

def delete_medications(
    medications_df,
    medication_ids=None,
    delete_all=False
):
    """
    Delete one, multiple, or all medications.

    Returns:
        DataFrame: Updated medication records.
    """

    if delete_all:
        return medications_df.iloc[0:0].copy()

    if medication_ids:
        updated_df = medications_df[
            ~medications_df[
                "medication_id"
            ].isin(medication_ids)
        ].copy()

        return updated_df

    return medications_df.copy()

Writing myutils.py

In [358]:
os.listdir(".")

['.env',
 '.gitignore',
 '.ipynb_checkpoints',
 'Development.ipynb',
 'medications.csv',
 'MediTrack Project Roadmap Infographic.png',
 'myutils.py',
 'Open Router API key.txt',
 'Python Project 1 - Part 1 Guidelines.pdf',
 'Python Project 1 - Part 2 Guidelines.pdf',
 'README.md']

In [364]:
import myutils

In [366]:
myutils.load_medications()

,medication_id,medication_name,ingredients_substances,symptoms_tags,dosage_frequency_value,dosage_frequency_unit,usage_safety_instructions,urgency_level,medication_type,dose_quantity,dose_unit,start_time,current_supply,refill_threshold,expiration_date,compliance_rating,api_generic_name,api_substances
0,1,Ibuprofen,Ibuprofen,NaN,8,Hours,Take with food,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Aspirin,Aspirin,NaN,6,Hours,Take with water,Low,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Panadol,Paracetamol,"headache, fever, pain",8,Hours,Take with water,Medium,NaN,NaN,NaN,08:00,20.0,5.0,2027-01-01,NaN,NaN,NaN

In [368]:
myutils.check_low_supply(5, 10)

True

In [370]:
myutils.search_medication_api("aspirin")[0]["brand_name"]

'Low Dose Aspirin'

In [372]:
myutils.get_random_wellness_spotlight()

{'type': 'Medication Spotlight',
 'content': 'Metformin helps manage blood sugar in type 2 diabetes. Take it with meals to reduce stomach upset, and report unusual muscle pain or extreme tiredness to your doctor.'}

# creating the app.py (streamlit)

In [381]:
%%writefile app.py

import streamlit as st
from datetime import datetime, timedelta

import myutils


# -----------------------------------------
# PAGE SETTINGS
# -----------------------------------------

st.set_page_config(
    page_title="MediTrack",
    page_icon="💊",
    layout="wide"
)


# -----------------------------------------
# LOAD SAVED MEDICATIONS
# -----------------------------------------

medications_df = myutils.load_medications()


# -----------------------------------------
# HEADER
# -----------------------------------------

st.title("💊 MediTrack")
st.caption("Digital Medication Tracker & Personal Health Record")


# -----------------------------------------
# SIDEBAR MENU
# -----------------------------------------

menu = st.sidebar.radio(
    "Menu",
    [
        "Add Medication",
        "Search Medications",
        "My Medications",
        "Wellness Spotlight"
    ]
)


# =========================================
# 1. ADD MEDICATION
# =========================================

if menu == "Add Medication":

    st.header("Add a New Medication")

    with st.form("add_medication_form"):

        medication_name = st.text_input(
            "Medication Name",
            placeholder="Example: Ibuprofen"
        )

        ingredients_substances = st.text_input(
            "Active Ingredients / Interacting Substances",
            placeholder="Example: Ibuprofen, Caffeine"
        )

        symptoms_tags = st.text_input(
            "Symptoms / Tags",
            placeholder="Example: headache, fever, pain"
        )

        col1, col2 = st.columns(2)

        with col1:
            dosage_frequency_value = st.number_input(
                "Dosage Frequency",
                min_value=1,
                value=8,
                step=1
            )

        with col2:
            dosage_frequency_unit = st.selectbox(
                "Frequency Unit",
                ["Hours", "Minutes"]
            )

        usage_safety_instructions = st.text_area(
            "Usage & Safety Instructions",
            placeholder="Example: Take with food"
        )

        urgency_level = st.selectbox(
            "Urgency / Critical Level",
            ["Low", "Medium", "High"]
        )

        start_time = st.time_input(
            "First Dose / Start Time"
        )

        col3, col4 = st.columns(2)

        with col3:
            current_supply = st.number_input(
                "Current Supply",
                min_value=0,
                value=0,
                step=1
            )

        with col4:
            refill_threshold = st.number_input(
                "Refill Threshold",
                min_value=0,
                value=5,
                step=1
            )

        expiration_date = st.date_input(
            "Expiration Date",
            value=(
                datetime.now()
                + timedelta(days=365)
            ).date()
        )

        submitted = st.form_submit_button(
            "Add Medication"
        )

    if submitted:

        if medication_name.strip() == "":
            st.error("Please enter a medication name.")

        elif ingredients_substances.strip() == "":
            st.error(
                "Please enter at least one active ingredient."
            )

        elif myutils.is_duplicate_medication(
            medications_df,
            medication_name
        ):
            st.warning(
                f"{medication_name} is already saved."
            )

        else:

            medications_df = myutils.add_medication(
                medications_df,
                medication_name,
                ingredients_substances,
                dosage_frequency_value,
                dosage_frequency_unit,
                usage_safety_instructions,
                urgency_level,
                symptoms_tags,
                start_time.strftime("%H:%M"),
                current_supply,
                refill_threshold,
                expiration_date.isoformat()
            )

            st.success(
                f"{medication_name} added successfully."
            )
            # =========================================
# 2. SEARCH MEDICATIONS
# =========================================

elif menu == "Search Medications":

    st.header("Search Medications")

    search_text = st.text_input(
        "Search by medication name, active ingredient, or symptom",
        placeholder="Example: paracetamol, headache, Panadol"
    )

    if st.button("Search"):

        if search_text.strip() == "":
            st.warning("Please enter a search term.")

        else:
            results = myutils.search_saved_medications(
                medications_df,
                search_text
            )

            if results.empty:
                st.info("No matching saved medications found.")

            else:
                st.success(
                    f"{len(results)} matching medication(s) found."
                )

                st.dataframe(
                    results[
                        [
                            "medication_name",
                            "ingredients_substances",
                            "symptoms_tags",
                            "dosage_frequency_value",
                            "dosage_frequency_unit",
                            "urgency_level"
                        ]
                    ],
                    use_container_width=True,
                    hide_index=True
                )

                risk_medications = (
                    myutils.check_shared_ingredient_risk(
                        medications_df,
                        search_text
                    )
                )

                if len(risk_medications) > 1:
                    st.warning(
                        "Potential overlapping ingredient risk: "
                        + ", ".join(risk_medications)
                        + " contain the searched ingredient."
                    )

Overwriting app.py